---
title: "Prioritizing barriers for restoring Pacific Salmon habitat connectivity"
output-file: "BCSRIF_2022_415.html"
Leads: "Canadian Wildlife Federation"
toc: true
---

## BCSRIF Project Summary

**Species Group:** Pacific Salmon  
**Location:** Upper Fraser, Lower Nicola Watershed, Lower Fraser, Skeena and Central Coast  
**Partners:** Lower Fraser Fisheries Alliance (LFFA) 
Central Coast Indigenous Resource Alliance (CCIRA) 
Upper Fraser Fisheries Conservation Alliance (UFFCA) 
Skeena Sustainability Assessment Forum Project Team (SSAF PT) 
Office of the Wet’suwet’en, Gitxsan Gitanyow, and Witset First Nation
Lhtako Dené Nation (LDN) 
Scw’exmx Tribal Council (STC) 
T’exelc, Williams Lake First Nation (WLFN) 
The Horsefly River Roundtable (HRR) 
The Pacific Salmon Foundation (PSF) 
BC Ministry of Land, Water and Resource Stewardship (MLWRS) 
BC Ministry of Forests (MOF)
BC Ministry of Transportation and Infrastructure (MOTI) 
DFO Salmonid Enhancement Program (SEP) 
University of British Columbia (UBC) 
  
**Organization:** Canadian Wildlife Federation  
**Session(s):** Data And Modelling To Support Decision Making  
**Presentation Date(s):** December 09, 2025  
**Speakers:** Nick Mazany-Wright  
**Abstract:**  
The Restoring freshwater connectivity for Pacific salmon project by the Canadian Wildlife Federation is a continuation and expansion of their current BCSRIF project (BCSRIF_2019_137). The goals of the 2023-2026 project are to develop up to seven indigenous led watershed connectivity remediation plans in Pacific salmon habitat; update three existing watershed connectivity remediation plans; improve the habitat suitability modelling and assessment techniques for BC salmon to allow for better prediction of important spawning and rearing habitat areas disconnected by both longitudinal and lateral barriers in conjunction with UNBC; identify and rank the most important barriers to fish passage caused by rail infrastructure and initiate development of an action plan to restore access to spawning and rearing habitat that is currently cut off by rail stream crossings; and improve the knowledge and application of best practices for stream crossings among practitioners in government and the private sector to prevent future unintended fragmentation of habitat through the development of a short course and supporting resources relating to stream crossings. Target areas for watershed plans include the Bowron River and Quesnel River watersheds as well as other yet to be determined.   


