---
title: "Research in support of Sarita Chinook as an Ecological Indicator and WCVI Chinook Salmon Rebuilding"
output-file: "BCSRIF_2022_332.html"
Leads: "Huu-ay-aht First Nations"
toc: true
---

## 📋 BCSRIF Project Summary

**Species Group:** Pacific Salmon  
**Location:** Sarita River watershed near Bamfield and Anacla, Barkley Sound, Westcoast Vancouver Island  
**Partners:** Nitinat hatchery
DFO Southcoast - StAD (?)
WCVI Indigenous Nations
LGL Limited  
**Agreement Period:** March 07, 4610301 to October 07, 4861522  
**Session(s):** Follow The Fish  
**Presentation Date(s):** December 04, 2025  
**Speakers:** Christine Gruman  
**Overview:**  
Huu-ay-aht First Nations will undertake work over a 3-year study period, to consider the applicability for the Sarita Chinook population as an ecological indicator for the COSEWIC listed West Vancouver Island, Ocean, Fall (South) population and the Westcoast Vancouver Island (WCVI) Management Unit. The proposed project will enumerate migration of Chinook smolts, monitor and evaluate salmon distribution, habitat use and spawning areas in the Sarita estuary and river system, consider predation impacts and study the nearshore marine habitat use and biological characteristics of Chinook Salmon in Numukamis Bay (which the Sarita River empties into) and Barkley Sound.    

