---
title: "Identifying factors that influence early marine survival of WCVI Chinook salmon"
output-file: "BCSRIF_2022_442.html"
Leads: "Pacific Salmon Foundation"
toc: true
---

## 📋 BCSRIF Project Summary

**Species Group:** Pacific Salmon  
**Location:** West Coast Vancouver Island  
**Partners:** Pacific Salmon Foundation 
DFO Science Branch
Mitacs  
**Agreement Period:** September 21, 4616924 to October 07, 4861522  
**Session(s):** Follow The Fish  
**Presentation Date(s):** December 04, 2025  
**Speakers:** Andrew Bateman  
**Overview:**  
Our project brings together a broad group of Indigenous and non-Indigenous collaborators to evaluate timing and causes of mortality in west coast Vancouver Island (WCVI) Chinook salmon during early marine residence. We will use PIT-tagging to estimate survival, and combine these estimates with individual-based measures of environmental stress using cutting-edge gene-expression tools (“Fit-Chips”). Additionally, we will monitor environmental DNA (eDNA) to determine key rearing habitats, availability of prey, and presence of predators and pathogens across spatial and temporal scales.

Our project will fill key information gaps pertaining to at-risk Chinook populations, prescribed for rebuilding under the Fisheries Act. Ultimately, the findings will help to inform targeted habitat restoration, protection, and enhancement efforts for WCVI Chinook salmon. Adding to ongoing collaborations with WCVI First Nations, DFO, local NGOs, and PSF’s Salmon Bottlenecks project, we will leverage extensive experience, expertise, and infrastructure already in place to deliver the most comprehensive investigation to date of early marine survival in WCVI Chinook salmon.   

