---
title: "Evaluating climate change scenarios for the Quesnel Watershed to determine flood, fire and temperature risks posed to Upper Fraser salmon stocks."
output-file: "BCSRIF_2022_399.html"
Leads: "University of Northern British Columbia, Department of Geography, Earth and Environmental Sciences"
toc: true
---

## 📋 BCSRIF Project Summary

**Species Group:** Pacific Salmon  
**Location:** Quesnel  
**Partners:** Upper Fraser Fisheries Conservation Association 
Horsefly River Roundtable
Cariboo Envirotech 
Fisheries and Oceans Canada - SEP & Science  
**Agreement Period:** March 07, 4610301 to October 07, 4861522  
**Session(s):** Salmon In A Changing Climate  
**Presentation Date(s):** December 02, 2025  
**Speakers:** Ellen Petticrew  
**Overview:**  
This project will focus on understanding the effects of climate change on salmon ecosystems and the direct effects of increasing water temperatures and wildfire-contaminated spawning habitat on interior Pacific salmon early life stages.  Improvements to hatchery infrastructure will aid Chinook enhancement and conservation efforts with collaborators at DFO and Upper Fraser Fisheries Conservation Alliance. Construction of a center of excellence will provide classroom/outreach space to provide First Nations training and community outreach, while specialized laboratory facilities will increase collaboration and salmon ecosystem research.  This project will build educational and research capacity, improve Chinook salmon culture and deliver to the adjustment of management protocols for existing Pacific salmon stocks in these areas and to the development of mitigations to address climate change.   

