---
title: "Democratizing Salmon Data through the Expansion of the Pacific Salmon Explorer"
output-file: "BCSRIF_2020_279.html"
Leads: "Pacific Salmon Foundation"
toc: true
---

## BCSRIF Project Summary

**Species Group:** Pacific Salmon  
**Location:** Fraser River  
**Partners:** None listed  
**Organization:** Pacific Salmon Foundation  
**Session(s):** Data And Modelling To Support Decision Making  
**Presentation Date(s):** December 09, 2025  
**Speakers:** Leah Honka and Eric Hertz  
**Abstract:**  
For over a decade, the Pacific Salmon Foundation’s Salmon Watersheds Program (SWP) has worked to democratize salmon data. Through support from BCSRIF, and additional funding sources, the SWP has expanded the Pacific Salmon Explorer – an online data visualization tool for Pacific salmon and their freshwater habitats – to all salmon-bearing regions in British Columbia and the Yukon. The SWP team has engaged with First Nations organizations, government scientists, and independent experts to compile and analyse data on salmon abundance, catch, productivity, and broad-scale habitat pressures to inform standardized assessments of biological status and habitat threats for Pacific salmon Conservation Units. By making data and assessments readily accessible, the SWP has supported numerous organizations, including COSEWIC, Ocean Wise, and the Central Coast Indigenous Resource Alliance, in decision-making for salmon conservation, management, and recovery.   


