---
title: "Mortality of released Pacific Salmon in the marine recreational fishery: new science and recommendations"
output-file: "BCSRIF_2019_058.html"
Leads: "University of British Columbia (Vancouver), Department of Forest and Conservation Sciences"
toc: true
---

## BCSRIF Project Summary

**Species Group:** Pacific Salmon  
**Location:** Pacific Ocean  
**Partners:** Moss Rock Foundation
Dr. Steve Cooke (Carleton University)
Ocean Tracking Network Canada
... 24 in total from year-end report  
**Organization:** Pacific Salmon Ecology and Conservation Laboratory, UBC  
**Session(s):** Fisheries Monitoring And Harvest Methods  
**Presentation Date(s):** December 09, 2025  
**Speakers:** Steve Johnston  
**Abstract:**  
Catch-and-release (CR) practices are a key component of fisheries management and have the potential to be increasingly used in future management scenarios. However, mortality associated with CR may be highly variable and influenced by environmental, physiological, and handling-related factors associated with marine recreational fisheries. Post-release mortality estimates used in management frameworks are based on studies that lacked the temporal and spatial scope necessary to define these rates. Our seven-year project has combined both telemetry tracking and holding study components to develop a wholesome understanding of the post-release experience of Chinook and coho salmon, and the factors that influence both short- and long-term mortality. Using acoustic telemetry, we tracked more than 1,800 Chinook and coho salmon captured and released by anglers along the BC coast to quantify post-release mortality. Additionally, we captured 730 Chinook and coho salmon and monitored their survival in land-based holding tanks for a minimum of 10 days to observe more specific mechanisms of mortality. We found that injury type and handling methods were key predictors of mortality, with blood loss, scale loss, and fin damage having more immediate effects, while eye injuries were more likely to drive latent mortality responses. Overall, Chinook salmon were more resilient to fishery interactions, and coho salmon were more susceptible to injuries related to fishery handling. We have produced 15 best-practice recommendations for anglers participating in marine recreational fisheries where one can expect to be required to release non-target individuals.   

**Bio:**  
Stephen Johnston, PhD Candidate and Wall Legacy Fellow, Pacific Salmon Ecology and Conservation Laboratory, UBC  

**Collaborators:**  
Sport Fishing Institute of British Columbia, Bamfield Marine Science Centre, Ocean Tracking Network, Pacific Salmon Foundation, Kintama Research, Gillard Pass Fisheries Society  


