---
title: "Determining the mechanisms of impacts of a changing climate on zooplankton in the Salish Sea using models and observations"
Leads: ""
toc: true
---

## 📋 BCSRIF Project Summary

**Species Group:** Pacific Salmon  
**Location:** Vancouver  
**Partners:** Fisheries and Oceans Canada - Science 
University of Washington, Oceanography 
Institute of Ocean Sciences   
**Agreement Period:** April 15, 4612903 to October 07, 4861522  
**Session(s):** Marine Stressors  
**Presentation Date(s):** December 04, 2025  
**Speakers:** (blank)  
**Overview:**  
University of British Columbia (UBC), in partnership with Ocean Sciences (DFO) and University of Washington, will use a combined approach to examine the impacts of climate change on the food available to out-migrating juvenile salmon and resident adult species  in the Salish Sea. Using both computer models and observational data, the team will focus on zooplankton responses to stressors such as ocean warming and increased atmospheric CO2. This information will be critical to identifying potential benefits or threats posed to wild Pacific Salmon populations in response to climate change.    

