---
title: "Chinook Salmon Assessments and WCVI Chinook Salmon Rebuilding in the Kaouk and Artlish Watersheds"
Leads: ""
toc: true
---

## 📋 BCSRIF Project Summary

**Species Group:** Pacific Salmon  
**Location:** Kaouk River and Artlish River watersheds located in Kyuquot Sound, Westcoast Vancouver Island  
**Partners:** DFO Southcoast StAD
WCVI Indigenous Nations
LGL Limited  
**Agreement Period:** March 07, 4610301 to October 07, 4861522  
**Session(s):** Follow The Fish  
**Presentation Date(s):** December 04, 2025  
**Speakers:** Timothy Sobey  
**Overview:**  
Ka:’yu:’k’t’h’/Che:k:tles7et’h’ First Nations (KCFN) will undertake work over a 3-year study period in the Kaouk and Artlish Rivers to fill in information gaps regarding the life history of two of three Chinook indicators for the West Vancouver Island, Ocean, Fall (North) population Conservation Unit. The project will build on stock assessment data collected over the past 10 years in the Kaouk and Artlish watersheds and will cover the life history from egg deposition by spawning Chinook to nearshore marine, in support of the WCVI Chinook rebuilding initiative.    

