---
title: "FRIM – Short term mortality holding and respirometry studies"
output-file: "BCSRIF_2022_454.html"
Leads: "Sport Fishing Institute of BC"
toc: true
---

## 📋 BCSRIF Project Summary

**Species Group:** Pacific Salmon  
**Location:** Bamfield  
**Partners:** UBC Salmon Ecology Lab
Bamfield Marine Sciences 
Huuayaht First Nation  
**Agreement Period:** April 15, 4612903 to October 07, 4861522  
**Organization:** Sport Fishing Institute of BC  
**Session(s):** Fisheries Monitoring And Harvest Methods  
**Presentation Date(s):** December 09, 2025  
**Speakers:** Owen Bird  
**Abstract:**  
This project will build on a previously funded Fisheries Related Incidental Mortality (FRIM) study led by the Sport Fishing Institute to expand the work to include Coho salmon, in addition to Chinook. This study will utilize best practices developed in the previous study to better understand FRIM in the recreational Coho fishery on West Coast Vancouver Island, and will be further advanced by a new component to study affects of fisheries interactions on fish metabolism. This information will be used to expand the Best Practices Handbook developed in 2020.    

