---
title: "Risk Assessment Method for Salmon – Development for Regional Implementation"
---

## 🧬 Project Summary

**Lead(s):** Christina Czembor  
**Division:** Regional Director's Office  
**Section:** Regional Director's Office  
**Location:** N/A  
**Status:** Ongoing  
**Theme:** Decision Support  
**PSSI Pillar:** 1-Conservation and stewardship  

**Overview:**  
**(1) WHAT IS BEING PROPOSED**

Hyatt et al. developed the Risk Assessment Method for Salmon (RAMS) in 2010 to
identify and prioritize factors that limit salmon production, both now and
under climate change. It was adapted from existing DFO risk assessment
frameworks and a risk assessment framework for fisheries in Australia, and
provides a standardized and semi-quantitative method to integrate ecosystem
data and expert opinion related to salmon survival across all their life
stages. The resulting list of ranked risks identifies both high priority
management needs and data gaps that require additional investigation.

RAMS has been applied in more than a half dozen watersheds for Chinook (ocean
and stream type), coho, and sockeye to inform Recovery Potential Assessments
under the Species at Risk Act and Rebuilding Plans under the Fish Stock
Provisions of the Fisheries Act. RAMS continues to evolve toward a standard
methodology flexible enough to assess risks at different scales and with
various levels of data availability. Included in those methods are: Regional
Salmon Information Tables that provide scientific information about freshwater
limiting factors for all major life history strategies of Pacific salmon
species; a deterministic Life History Model template completed using relevant
population data; an Ecosystem (Habitat) Status Report template completed using
existing habitat and ecosystem information; and a Risk Assessment Matrix
template completed during a RAMS workshop, currently in Excel format.

Areas of improvement for RAMS have been identified to facilitate regional
implementation. Several components will be addressed by the existing project
team, but some are beyond the capacity and/or expertise of the team and are
the purpose of this proposed work. These include: (A) updates to the Regional
Salmon Information Tables. This resource has not been updated since inception
and significant new science is available to maintain relevance. Inclusion of
marine information is also necessary to understand the bottlenecks to salmon
across all their life stages. And (B) a conversion from the Excel-based Risk
Assessment Matrix template to an R program based on a relational database with
an interactive user interface. The Excel-based template is functional but does
not allow for visualization of the many ecosystem components that are
aggregated to understand risk; complex analysis of relationships between
indicators and limiting factors; or hierarchical meta-analyses of data gaps
and risk across stocks to facilitate prioritization of monitoring and
research. Conversion to a relational database with a user interface will allow
for this functionality.

**(2) OUTCOMES:**

A updated, robust RAMS framework applicable for all salmon species structured
for continuous learning and updating, that is user-friendly for DFO and non-
DFO technical staff. Specifically, 1\. Updated Regional Salmon Information
Tables by life stage and ecosystem unit, including indicators, benchmarks, and
guidance for RAMS facilitators. Request is for two BI-02s to update through
existing literature and engage with DFO and other scientists (e.g., Dr.
Jonathon Moore’s lab at SFU, Institute of Ocean Sciences oceanographers) to
facilitate addition of freshwater and marine indicators and information. The
team will pilot the tables for use in rebuilding and recovery processes and
update as needed. 2\. Updated Risk Assessment Matrix template from Excel to an
R-based program and backend database. This will require specialized coding
expertise either through hiring or contract.  
3\. Workshop(s) with relevant DFO staff will be used to scope the structure
and functionality required. 4\. Updates to the RAMS methodology and support
work will require 0.35 FTE (Full Time Equivalents) for a BI-03.

**(3) THE MANAGEMENT QUESTION(S) ADDRESSED**

RAMS will prioritize risks to salmon stocks across the 3 Hs of Habitat,
Harvest, and Hatcheries by identifying management and mitigation options most
likely to result in successful restoration and rebuilding, which will support
decision making in each of the 3Hs. It will prioritize scientific research and
monitoring to address key knowledge gaps and integrate knowledge across
disciplines inside and outside DFO. RAMS will support and standardize the
legislated requirements for rebuilding plans under the Fish Stock Provisions
and Recovery Potential Assessments under SARA.



[⬅ Back to Home](../index.qmd)
