---
title: "Assessment of SEP Chinook and Coho broodstock ELISA screening data by modelling for explanatory variables, and yearling DFAT prevalence data by modelling for predictive variables."
description: "Screening salmon brood stock for bacterial kidney disease has allowed hatcheries to reduce the disease in young salmon and returning adults. Hatcheries now have 16 years of disease test data along with genetic (parentage) information. This hatchery study collects disease data and genetics from Chinook and coho at the Spius, Puntledge, and Nitinat hatcheries
 to model variables that could improve hatchery methods."
author: "Amy Long"
toc: true
---

## 📋 Project Summary

**Lead(s):** Amy Long  
**Division:** Aquatic Diagnostics, Genomics and Technology (ADGT)  
**Section:** Aquatic Animal Health  
**PSSI Pillar:** 2-Salmon enhancement  
**Session:** NA  
**Presentation Date:** TBD  
**Speakers:** NA  
**Hosts:** NA  

**Overview:**  
Screening salmon brood stock for bacterial kidney disease has allowed hatcheries to reduce the disease in young salmon and returning adults. Hatcheries now have 16 years of disease test data along with genetic (parentage) information. This hatchery study collects disease data and genetics from Chinook and coho at the Spius, Puntledge, and Nitinat hatcheries
 to model variables that could improve hatchery methods.   

**Activities:**  
__Objective 1. Identification of potential BKD predictor values in juvenile salmon.__
For this objective, we will analyze the DFAT prevalence of yearling stocks prior to release to identify potential predictor variables. Known risk factors for infection (faecal-oral route) include circular tanks versus raceways; surface water versus ground water; winter water temperatures; antibiotic treatment, and whether ELISA based screening for yearling program is used or not.

**Objective 2. Evaluate effect of raising ELISA threshold values.** 
A simulation model will be used to model the effect of increasing the positive-negative threshold optical density value. This would involve use of the diagnostic sensitivity and specificity for ELISA given in the literature, and existing ELISA data where the positive-negative threshold optical density value were increased. The current threshold used by SEP is <0.1 which may lead to exclusion of uninfected females hence the desire to model threshold value changes.

[⬅ Back to Home](../index.qmd)
