---
title: "Quantifying Yukon Chinook migration mortality and its implications for fisheries management and rebuilding under the Fish Stock Provisions of the Fisheries Act"
---

## 🧬 Project Summary

**Lead(s):** Brendan Connors, Adam O'Dell  
**Division:** Stock Assessment and Research (StAR)  
**Section:** Yukon/Transboundary Rivers Area Salmon Stock Assessment  
**Location:** ["Yukon River"]  
**Status:** Ongoing  
**Theme:** Salmon Monitoring  
**PSSI Pillar:** 1-Conservation and stewardship  

**Overview:**  
Yukon River Chinook salmon have experienced declines in returns in recent
decades culminating in four of the lowest returns on record in 2020-2023.
These declines have put immense strain on the subsistence communities and Fish
Nations that historically depended upon Chinook salmon throughout the Yukon
River. They have also impacted the ability of the United States and Canada to
meet escapement goals under the Pacific Salmon Treaty’s Yukon River Agreement,
and are likely to have resulted in the Stock Management Unit, which is
scheduled to be prescribed by regulation under the amended Fisheries Act in
2023/2024, to fall below its Limit Reference Point. In recent years large
numbers (33%-52%) of returning Canadian-origin Chinook salmon have gone
“missing” between sonar assessments at the mouth of the Yukon River and ~2000
km upriver at the border between Alaska and Canada. This has severely
undermined the efficacy of fisheries management measures within the Alaskan
portion of the river. A leading hypothesis for these missing fish is en route
mortality due to heat stress (JTC 2020), which has been documented along with
opportunistic observation of premature mortalities in Yukon River Chinook
Salmon when spawning migration water temperatures exceed 18°C (Biela et al.
2020; 2022). However, direct estimates of en route mortality do not exist and
a recent CSAS regional peer review (DFO 2022) identified the drivers and
magnitude of en route mortality, and their consequences for management advice,
as a critical uncertainty.

We propose to carry out a 3 year radio-telemetry project to quantify en route
mortality of Yukon Chinook in relation to freshwater environmental conditions
along their up to ~3000km migration from the mouth of the Yukon river to
headwater spawning grounds. We will then use these estimates of en route
mortality to evaluate the sustainability of the current aggregate escapement
goal for Canadian-origin Yukon Chinook, and rebuilding potential of component
Conservation Units (Connors et al. 2022) to inform analyses to meet the Fish
Stock Provisions of the revised Fisheries Act for the Stock Management Unit.
We are specifically seeking funding to extend radio-tracking infrastructure
(towers and aerial overflights) into Canada to take advantage of an Alaska
Department of Fish and Game (ADF&amp;G) project that will tag and track ~600
Chinook salmon in the Alaskan Portion of the Yukon River.

The management question being addressed by this project is: what is the
magnitude of en route mortality in Canadian-origin Yukon Chinook and what are
its consequences for international and domestic fisheries management,
rebuilding potential, and integrated planning.

The specific outcomes of this project include:

  1. estimates of migration speed, timing, and en route mortality of Canadian-origin Yukon Chinook, by Conservation Unit and river section, in relation to freshwater environmental conditions; and

  2. quantitative evaluation of the consequences of a range of en route mortality (based on study) for the sustainability of alternative aggregate escapement goals and rebuilding potential.



[⬅ Back to Home](../index.qmd)
