---
title: "Improving baseline knowledge of environmental conditions in Vancouver Islands fjords through observations and modelling, with a focus on hypoxia dynamics, climate change, and the potential implications for Pacific salmon"
---

## 🧬 Project Summary

**Lead(s):** Laura Bianucci  
**Division:** Ocean Sciences (OSD)  
**Section:** Ocean Modelling and Prediction  
**Location:** ["Clayoquot Sound"]  
**Status:** Ongoing  
**Theme:** Ecosystem Monitoring  
**PSSI Pillar:** 1-Conservation and stewardship  

**Overview:**  
This project supports ongoing observational and modelling work in the fjords
of the west coast of Vancouver Island (WCVI), with the goal of better
understanding oxygen dynamics in this region. Modelling work started in fiscal
year 2021-22 and main deliverables (a coupled physical-biogeochemical model of
WCVI, south of Kyuquot) are expected by the end of 2023-24. A small
observational component started during 2021-22 and has grown in scope every
year. Through PSSI, we have two main goals: to create a monitoring program for
Clayoquot Sound in 2023-24 (that will ideally extend to 2025-26) and to
support and extend modelling efforts in the WCVI.

Specifically, we propose the following: a. Establish a Clayoquot Sound
Monitoring Program in collaboration with the local First Nations (FN) and
other organizations (Hakai Institute and Nature Trust of BC). Talks with all
involved parties started in 2022-23; the plan is to provide training and
equipment to the FN so they can use their vessels to perform monthly
conductivity-temperature-depth (CTD) sampling throughout Clayoquot Sound (45
stations). These observations will support ongoing modelling work and will
provide an important baseline of environmental conditions (including oxygen)
throughout the year. This baseline is needed to understand the present-day
environment experienced by migrating Pacific salmon. Without this baseline, it
will be difficult to assess the effects of climate change in salmon
populations and migrating routes.

b. Hire a term PC3 to contribute to the progress of the coupled physical-
biogeochemical model for the west coast of Vancouver Island. In particular,
this PC3 will lead the simulation of future scenarios and will act as a
liaison with salmon experts, to ensure that the outputs of our simulations are
useful for population distribution modelling and other salmon-related
projections.

c. Hire a term EG4 to contribute towards DFO-led fieldwork in the WCVI inlets
as well as data processing and management. For instance, technical support is
needed for the development/improvement of weather stations and the maintenance
of the weather station network (their data are crucial for forcing the surface
of coastal ocean models), as well as for support with mooring
deployment/servicing and opportunistic CTD sampling (e.g., while servicing
weather stations). Furthermore, the EG4 will be needed to manage the inflow of
data from the Clayoquot Sound Monitoring Program.

Management questions: Near-surface hypoxia (as shallow as 12 m) has been
recently identified in Herbert Inlet, Clayoquot Sound (Rosen et al., 2022,
doi:10.3389/fmars.2022.1000041). The historical record in the region is
sparse, but it suggests that shallow hypoxia is found occasionally in this
inlet. Are salmon runs affected by low-oxygen conditions near the surface in
the fjords? Do these shallow hypoxic events constrain/restrict salmon habitat
during their migration? Are these shallow hypoxic events increasing in
frequency or can they be predicted in any way? (e.g., more common during
marine heat waves or during positive/negative ENSO years, etc.). In order to
address these questions, as well as the more generic question “What is the
environment that salmon encounter during their migration into and out of the
rivers, i.e. while they swim through fjords?”, we need to establish a
monitoring program throughout the fjords of interest. A consistent sampling
program in the next few years will create the baseline from which we will be
able to assess future changes; and a monitoring program that continues in the
future will make sure we can identify any climate-related change in the
fjords’ environment. Furthermore, by combining observations and high-
resolution (tens of meters) ocean models, we will be able to understand the
mechanisms that drive oxygen (and other – e.g., acidification) conditions in
the inlets, and predict how these will be impacted by a changing climate. The
modelling work proposed here for the WCVI will allow for the first study of
the impacts of future conditions in these fjords.



[⬅ Back to Home](../index.qmd)
