---
title: "Changing coastal productivity: Using sediment cores, water properties and archived plankton data to identify changes at the bottom of the food web in BC’s coastal waters"
description: "Has climate change reduced the amount of plankton at the bottom of the food web in BC waters, reducing the carrying capacity for salmon? Have smaller phytoplankton replaced diatoms, lengthening the food chain and making food less nutritious for salmon? This study uses chemical markers in sediment cores and water samples to investigate food web changes in BC coastal inlets."
author: "Sophia Johannessen"
toc: true
---

## 📋 Project Summary

**Lead(s):** Sophia Johannessen  
**Division:** Ocean Sciences (OSD)  
**Section:** Ecology and Biogeochemistry  
**PSSI Pillar:** 1-Conservation and stewardship  
**Speaker Theme:** Uncategorized  
**Presentation:** December 02, 2025  

**Overview:**  
Has climate change reduced the amount of plankton at the bottom of the food web in BC waters, reducing the carrying capacity for salmon? Have smaller phytoplankton replaced diatoms, lengthening the food chain and making food less nutritious for salmon? This study uses chemical markers in sediment cores and water samples to investigate food web changes in BC coastal inlets.   

**Activities:**  
•	Analyze biomarkers in existing sediment core samples 
•	Collect and analyze one additional sediment core from Juan Perez Sound, Haida Gwai (ship-time approved: Mooring cruise, August 2025)
•	Quality control of data for archiving
- Interpret all inlet sediment cores: sedimentation rates, carbon accumulation rates, proportions of marine and terrigenous organic matter, determine whether marine and/or terrigenous flux has changed over time

[⬅ Back to Home](../index.qmd)
