---
title: "Follow the Fish: An integrated Chinook salmon assessment and monitoring program for the West Coast of Vancouver Island"
---

## 🧬 Project Summary

**Lead(s):** Jessy Bokvist  
**Division:** Stock Assessment and Research (StAR)  
**Section:** South Coast Area Salmon Stock Assessment  
**Location:** ["Stamp River","Sarita River","Nitinat","Barkley Sound"]  
**Status:** Ongoing  
**Theme:** Salmon Monitoring  
**PSSI Pillar:** 1-Conservation and stewardship  
**Speaker Theme:** Salmon population monitoring and assessment  

**Overview:**  
Follow the Fish (FtF), is an overarching research program being developed to
provide urgently needed information for effective conservation and rebuilding
of West Coast of Vancouver Island (WCVI) Chinook salmon populations. WCVI
Chinook are listed under bill C-68 and are threatened by local extinction and
poor marine survival, with high mortality thought to occur during the early
marine phase. Through the recent multi-stakeholder WCVI Chinook Salmon Marine
Risk Assessment (MRA) process multiple data gaps were identified for potential
factors that contribute to poor early marine survival. Many salmon surveys
have been conducted over the years, but few have been able to access shallower
areas within the sounds off the West Coast, where ocean-type Chinook may
reside for up to their first year at sea. Characterizing environmental
variables of these nearshore ecosystems in addition to the health and
condition of residing Chinook salmon is critical to understanding which
factors may be limiting survival. To address data gaps, in 2020 a highly
collaborative assessment program in nearshore areas within Sounds on the WCVI
was piloted to capture juvenile Chinook salmon in their first winter at sea
using microtrolling technology. Building on the successful implementation and
collaboration in this program, FtF aims to expand the assessment and
monitoring of WCVI Chinook both spatially and temporally to track fish
throughout their first year of life and identify limiting factors related to
growth and size-specific survival. The FtF program will focus on assessing
Chinook salmon originating from Stamp River, Sarita River and Nitinat River
populations in Barkley Sound as indicators of WCVI Chinook. Stamp River is an
existing indicator for WCVI Chinook, and existing programs and infrastructure
can enable relatively high rates of juvenile captures across the early marine
phase. Previous microtrolling efforts have demonstrated these populations are
detected in nearshore areas throughout WCVI Sounds over the winter through
capture of hatchery and wild fish. Although these populations are
predominately hatchery origin fish, contrasts will be made, where possible,
between wild and hatchery fish to understand how factors limiting survival and
growth may differ. Salmon will be captured at multiple time points throughout
their life cycle including in the Nitinat River Hatchery and Robertson Creek
Hatchery, in-river (rotary screw trap and/or beach seining), in estuary (beach
seining/purse seining), and in nearshore marine environments (purse
seining/microtrolling). At each time point, individual fish will be sampled to
assess health and condition (infectious agents, Fit-Chip gene expression
profiles, stomach contents, contaminants, lengths, weights, and clinical
signs) and stock of origin, paired with environmental data including physical
oceanography (temperature, oxygen, pH salinity, fluorescence) and biological
oceanography (chlorophyl, zooplankton). Scale samples from individual fish
will be used to compare relative rates of growth, based on circulus spacing,
across life stages and populations to assess the impact of health, condition
and environmental factors. Otolith samples taken concurrently will be used to
assess relative size-specific survival across time points and populations.
This can be achieved by characterizing the fork length to otolith radius
relationship for smolts at ocean entry and then using otolith microchemistry
for individuals who survive to subsequent time points. Broad distributional
trends in how WCVI Chinook migrate will be investigated with microtrolling by
capturing Northward migrating Barkley origin fish in Clayoquot, Nootka,
Kyuquot and Quatsino Sound. Chinook intercepted during microtrolling that are
not of Sarita, Stamp or Nitinat origin will be similarly sampled for
comparisons. Many current departmental research programs are collecting
datasets on salmon populations and their ecosystems that can be incorporated
into the FtF program for a comprehensive assessment of factors limiting
survival of WCVI Chinook. FtF is in discussion and working alongside both
internal and external collaborators to ensure datasets are integrated into FtF
(see project linkages). Existing DFO datasets from researchers across branches
will be synthesized alongside relevant datasets produced by external
collaborators. Throughout our FtF project timeline, we aim to incorporate
relevant datasets through new collaborations and outreach. This approach will
highlight data gaps that are not currently being addressed through either
departmental or external research groups and future research avenues. Data
outputs from this program will directly contribute to the WCVI Chinook
rebuilding plans and will be distributed across to project collaborators for
use in their programs. Knowledge on differential size-specific survival both
across the early marine phase and between wild and hatchery stocks will have
impacts on SEP management decisions for hatcheries and may inform harvest
strategies for WCVI Chinook populations. Characterizing differential growth
across the early marine phase will have important implications for restoration
activities (e.g., limited prey availability) and stock management e.g.,
(mitigating impacts on periods and areas of critical growth). Overall, data
outputs can be incorporated into pre-season and in-season forecasting and
other WCVI Chinook models.



[⬅ Back to Home](../index.qmd)
