---
title: "Barkley Sound and Clayoquot Sound Krill Monitoring"
description: "Krill, a type of zooplankton, are a critical component of the marine food webs and important part of juvenile salmon diets. This ecosystem monitoring program collects krill on a monthly basis in two key feeding areas for early marine juvenile salmon along the west coast of Vancouver Island. We are monitoring how the amount and nutritional value (fats, protein and total energy) of krill varies with season and ocean conditions (temperature, salinity, and oxygen)."
author: "Akash Sastri, Kelly Young"
toc: true
---

## 📋 Project Summary

**Lead(s):** Akash Sastri, Kelly Young  
**Division:** Ocean Sciences (OSD)  
**Section:** Ecology and Biogeochemistry  
**PSSI Pillar:** 1-Conservation and stewardship  
**Session:** Marine stressors  
**Presentation Date:** February 04, 2025  
**Speakers:** Akash Sastri, Kelly Young  
**Hosts:** Strahan Tucker  

**Overview:**  
Krill, a type of zooplankton, are a critical component of the marine food webs and important part of juvenile salmon diets. This ecosystem monitoring program collects krill on a monthly basis in two key feeding areas for early marine juvenile salmon along the west coast of Vancouver Island. We are monitoring how the amount and nutritional value (fats, protein and total energy) of krill varies with season and ocean conditions (temperature, salinity, and oxygen).   

**Activities:**  
•	Monthly (February-November) oceanographic (including collection of biotoxin samples for Dr Ross' PSSI program) and zooplankton sampling in Barkley Sound and continue surveys of established stations in Clayoquot Sound   
•	Collect and analyze krill samples for total lipid, protein, and energy density measurements: 
•	 Zooplankton sample enumeration; analysis and QAQC of phytoplankton, chlorophyll-a, salinity and nutrient samples, and CTD data
•	Annual analysis of seasonal development of the two key euphausiid species in Barkley and Clayoquot Sounds
•	Present results at the annual State of the Ocean Meeting

[⬅ Back to Home](../index.qmd)
