---
title: "Mechanistic modelling to link hydrology to juvenile salmon habitat quality and productivity"
---

## 🧬 Project Summary

**Lead(s):** Sean Naman  
**Division:** Ecosystem Sciences (ESD)  
**Section:** Freshwater Ecosystems  
**Location:** ["Thompson"]  
**Status:** Ongoing  
**Theme:** Decision Support  
**PSSI Pillar:** 1-Conservation and stewardship  
**Speaker Theme:** Freshwater ecosystems and stressors  

**Overview:**  
Hydrology is a key determinant of salmon productivity and persistence in
freshwater and is rapidly changing in many areas from human activities and
climate warming. Yet, it remains challenging to make explicit predictions
about how hydrology influences salmon. We aim to advance a mechanistic and
tractable modelling framework that links hydrology (flow and temperature) to
local-scale habitat availability and productivity potential of stream-rearing
juvenile salmon. The proposed approach integrates well-established theory of
geomorphology and fish energetics to predict how juvenile salmon rearing
habitat availability and productivity potential is influenced by dynamic flow
and temperature regimes (Fig. 1). The approach aims to be accessible by using
a tractable set of inputs that would emerge from typical field habitat
monitoring and is applicable across different systems and salmonid species. We
propose rolling out this modelling framework as part of a larger watershed-
scale research program in the North Thompson, where we have established an
extensive field monitoring network of flow, temperature, and habitat
conditions that would be direct model inputs. Ongoing intensive monitoring of
juvenile coho populations and physiological condition (D. Patterson proposal)
in these systems will inform model validation. For example, modelled
predictions could be directly compared to measures of coho abundance,
production, or physiological condition.

We anticipate 3 main outcomes from the work: (1) a modelling framework and
interface (e.g., R Shiny App); (2) predictions of how juvenile coho rearing
habitat availability and productivity potential responds to diverse flow and
temperature regimes across tributaries of the North Thompson; and (3) advice
to internal and external clients for setting environmental flow guidelines
under dynamic hydrologic conditions. For example, the work will directly plug
into ongoing engagement with the Thompson-Shuswap Environmental Flows
Committee, which is actively developing flow management guidelines and drought
response thresholds for the region. Further, the modelling framework will
provide a platform to explore the potential consequences of climate and land
use impacts on flows and temperatures, e.g., based on broader-scale, climate
averaged temperature and flow projections under climate change (J. Iacarella
proposal). This would provide a powerful, yet computationally simple and
accessible way to explore and communicate the dynamic relationships between
flows and salmon in a warming world. Overall, the approach is easily
extendable to other systems and salmonid species, thus could become a widely
used tool across the Province.

Approaches to predict biological responses to flow are integral to numerous
management issues. We envision the modelling framework informing regulatory
decision-making by FFHPP related to flow alterations (e.g., hydro operations
or water withdrawals), as well as land use and restoration planning. Our work
fills a gap for these applications given that existing instream flow modelling
tends to either be static and descriptive and thus not applicable to dynamic
conditions, or have prohibitively steep information and computational
requirements. This is a 3-year project that would support two parallel
elements: (1) collection of habitat, flow, and temperature data in coho
rearing tributaries across the North Thompson; and (2) development of model
structure and interface. Manuscript and report preparation and client
engagement will occur primarily in years 2 and 3.



[⬅ Back to Home](../index.qmd)
