---
title: "Development of geospatial tools for large-scale freshwater salmon habitat assessment by the Freshwater Spatial Ecology Program"
---

## 🧬 Project Summary

**Lead(s):** Josie Iacarella  
**Division:** Ecosystem Sciences (ESD)  
**Section:** Freshwater Ecosystems  
**Location:** N/A  
**Status:** Ongoing  
**Theme:** Decision Support  
**PSSI Pillar:** 1-Conservation and stewardship  

**Overview:**  
This project represents continued support for the Freshwater Spatial Ecology
Program (Freshwater Ecosystems Section, ESD) which is providing three main
outputs at a province wide scale that are critical for salmon management:
geospatial layers to evaluate salmon habitat, salmon habitat suitability under
current and future climate conditions, and cumulative effects on salmon
freshwater habitat. Through these outputs, the program is working to address a
very large gap in DFO’s understanding of where there is environmentally
suitable and healthy habitat for salmon in freshwater, where there is at-risk
habitat, and how this relates to salmon productivity at large spatial scales.
This information is essential to meaningfully conduct any management
prioritization related to the reliance of salmon populations on freshwater
habitats, but is challenging to obtain given the extensive spatial scale of
the Pacific Region and limited data.

Expected outcomes for Year 1: (1) Modelled and mapped August mean stream
temperatures for 20-year time intervals across climate change scenarios; (2)
Collation of remote sensing data for BC and beginning analysis to identify
riparian and off channel habitat for salmon; (3) Maps of experimentally-
derived thermally tolerable and intolerable streams under climate change
conditions across BC linked to known locations of juvenile habitat use; (4)
Completion of thermal growth experiments from egg to fry for two populations
of coho under naturally variable stream conditions and +2/+4 °C temperature
treatments; (5) Modelled and mapped cumulative effect scores for salmon
spawning habitat across the Fraser basin (to be extended province wide
provided ongoing funding), and assessment of change in cumulative effects
seasonally and over time delivered as a CSAS Research Document for FFHPP
Integrated Planning; (6) Modelled and mapped environmentally suitable streams
(and uncertainty estimation) under current and future climate conditions for
all 5 Pacific salmon species across BC; and (7) Spatial analysis of modelled,
climate averaged flow and stream temperature based threats on salmon
ecosystems under climate change in the Thompson-Nicola region delivered as a
CSAS Science Response for FFHPP Integrated Planning for Salmon Ecosystems.



[⬅ Back to Home](../index.qmd)
