---
title: "Feasibility of Estimating Chilko River Smolt Abundance Using Upward- and Side-Looking SONAR Methods"
---

## 🧬 Project Summary

**Lead(s):** Daniel Doutaz  
**Division:** Stock Assessment and Research (StAR)  
**Section:** Fraser and Interior Area Salmon Stock Assessment  
**Location:** ["Chilko"]  
**Status:** Ongoing  
**Theme:** Salmon Monitoring  
**PSSI Pillar:** 1-Conservation and stewardship  
**Speaker Theme:** Salmon population monitoring and assessment  

**Overview:**  
Chilko Sockeye salmon represent the only wild Sockeye indicator stock in the
Fraser watershed. The annual Chilko Lake Sockeye smolt assessment
(1951-present) comprises the only long-term time series data available to
assess juvenile recruitment, and freshwater and marine productivity for wild
Fraser River Sockeye salmon. Since program inception, Sockeye smolts have been
enumerated during their out-migration from Chilko Lake using a traditional
fish counting weir and photographic sampling/counting techniques. During the
first six decades of the program (1951-2012), interruptions in weir operation
were relatively rare: in only three years (1979, 1993, 2006) did early
freshets necessitate removal of the weir before the vast majority of smolts
had migrated from Chilko Lake.

Recently, unusually early freshets have been experienced in the Chilko
watershed that have translated into high and variable water conditions much
earlier in the season. As such, DFO Stock Assessment crews were not able to
operate the weir in 2015 due to high water flows, and have had to remove the
weir structure prior to the completion of smolt migration on numerous other
recent years (e.g., 2019). The observed increase in the frequency of early
freshets in the Chilko watershed is consistent with predicted hydrographic
changes for interior BC streams as a whole in response to climate variability,
with the average timing of the spring freshet expected to continue shifting
earlier as air temperatures rise. The future of operating the Chilko Sockeye
smolt weir is in jeopardy given the current trend related to the timing,
frequency, and strength of the spring freshets. If proven effective, the SONAR
method would provide an alternate assessment method for the Chilko watershed
that could be quickly employed in years when high flows either prevent the
installation of the weir at the beginning of the migration, or necessitate the
removal of the weir before the smolt migration is largely complete.

The objective of this work is to test the feasibility of using upward-looking
SONAR technology to assess daily abundances of Chilko Lake sockeye smolts as
they migrate downstream through the Chilko River. This technology has proven
to be effective for enumerating migrating smolts in comparable rivers in
Alaska. The reliably of the method will be evaluated based on how well the
daily SONAR-derived abundance indices predict the daily migration totals
observed at the counting weir that is deployed annually on the Chilko River. A
pilot study employing this technology was initiated within the Chilko
watershed in the spring of 2021, and following two consecutive years of data
collection the results appear to be promising; however, in both 2021 and 2022,
water levels have been below seasonal averages and we have yet to experience a
high-water event with the SONARs in place. Additional years of this project
are therefore required before any conclusions can be made regarding the
effectiveness of this technology as a substitute for the currently employed
counting weir on the Chilko River.



[⬅ Back to Home](../index.qmd)
