---
title: "Barkley Sound and Clayoquot Sound acoustic monitoring of salmon and salmon prey"
description: "Acoustic tools can provide important information on salmon ecology (food web) and salmon survival in marine areas. These salmon habitat and abundance monitoring studies use multi-frequency echosounders from mooring stations and mobile units in West Coast Vancouver Island sounds and the Salish sea to measure aspects of salmon forage species (zooplankton, krill, and Pacific herring) and count juvenile and adult salmon along their migration."
author: "Stephane Gauthier"
toc: true
---

## 📋 Project Summary

**Lead(s):** Stephane Gauthier  
**Division:** Ocean Sciences (OSD)  
**Section:** Ecology and Biogeochemistry  
**PSSI Pillar:** 1-Conservation and stewardship  
**Speaker Theme:** Uncategorized  
**Presentation:** December 03, 2025  

**Overview:**  
Acoustic tools can provide important information on salmon ecology (food web) and salmon survival in marine areas. These salmon habitat and abundance monitoring studies use multi-frequency echosounders from mooring stations and mobile units in West Coast Vancouver Island sounds and the Salish sea to measure aspects of salmon forage species (zooplankton, krill, and Pacific herring) and count juvenile and adult salmon along their migration.   

**Activities:**  
There are four key objectives for this project, with extensive processing and analyses of fisheries acoustics data:
1) Continue and build on time-series of forage species in the area using new and existing acoustic survey data (krill, Pacific herring, small coastal pelagic species)
2) Continue time-series of potential adult Chinook (large acoustic targets) in the area based on new and existing acoustic survey data
3) Retrieve and deploy autonomous inverted echosounder moorings at strategic locations to monitor juvenile salmon and salmon prey
4) Provide data reports and manuscripts summarizing the results from this project

[⬅ Back to Home](../index.qmd)
