---
title: "SHERLOCK assay for rapid genotyping applications"
---

## 🧬 Project Summary

**Lead(s):** Eric Rondeau, Tim Healy, Kyle Wellband  
**Division:** Aquatic Diagnostics, Genomics and Technology (ADGT)  
**Section:** Molecular Genetics  
**Location:** ["Puntledge River"]  
**Status:** Ongoing  
**Theme:** Innovation & Diagnostics  
**PSSI Pillar:** 2-Salmon enhancement  
**Speaker Theme:** Genetics and adaptation  

**Overview:**  
The objective of this project is to adapt and test the use of SHERLOCK lateral
flow-type assays to assess their viability / useability for rapid field-
deployable genetic assays for SEP management applications.

The specific case study that we will use as a proof of concept for this
technology is the GREB1L gene in Puntledge River Chinook Salmon. GREB1L is a
gene that explains a large amount of the variation in run timing for Chinook
Salmon. Specific SNPs in the GREB1L gene are currently used as diagnostic
genetic markers to retroactively distinguish between summer and fall runs of
Chinook in the Puntledge River Hatchery. These markers have two alleles one of
which is primarily carried by early returning Chinook Salmon and the other by
late returning salmon. Current management of enhancement at the Puntledge
River Hatchery uses a date threshold to ensure most &quot;summer run&quot; fish carry
the early-run allele to preserve the genetic integrity of this population
segment. Rapid in-season genotyping results would allow more accurate and
expanded use of available broodstock for the Puntledge summer run. SHERLOCK
assays are field deployable genotyping assays that can generate a result in
under an hour and may provide this capacity to enhancement efforts in the
Puntledge River. The technology has previously been demonstrated for rapid
genotyping purposes including GREB1L markers in California populations of
Chinook Salmon.



[⬅ Back to Home](../index.qmd)
