---
title: "Intergenerational transfer and parental origins of DNA methylation variation in Coho and Chinook Salmon"
description: "Chemical reactions in a salmon body decide which genes are expressed in a process called “DNA methylation.” This hatchery genetics study sequences methylation across the genome to compare between hatchery and natural origin to see if salmon offspring inherit DNA methylation from parents (epigenetics) and how this could inform hatchery breeding methods. "
author: "Eric Rondeau, Tim Healy, Kyle Wellband"
toc: true
---

## 📋 Project Summary

**Lead(s):** Eric Rondeau, Tim Healy, Kyle Wellband  
**Division:** Aquatic Diagnostics, Genomics and Technology (ADGT)  
**Section:** Molecular Genetics  
**PSSI Pillar:** 2-Salmon enhancement  
**Session(s):** hatcheries  
**Presentation Date(s):** December 09, 2025  
**Speakers:** Eric Rondeau, Tim Healy, Kyle Wellband  
**Hosts:** Cory Lagasse; Tim Healy; Eric Rondeau; Kyle Wellband  

**Overview:**  
Chemical reactions in a salmon body decide which genes are expressed in a process called “DNA methylation.” This hatchery genetics study sequences methylation across the genome to compare between hatchery and natural origin to see if salmon offspring inherit DNA methylation from parents (epigenetics) and how this could inform hatchery breeding methods.    

**Activities:**  
Not Listed

## 🧬 BCSRIF Metadata

**Species Group:**   
**Location:**   
**Agreement Period:** TBD to TBD  
**Partners/Collaborators:**   

[⬅ Back to Home](../index.qmd)
