---
title: "Adaptive genetic variation and climate change resilience in Canadian Pacific salmon"
---

## 🧬 Project Summary

**Lead(s):** Eric Rondeau, Tim Healy, Kyle Wellband  
**Division:** Aquatic Diagnostics, Genomics and Technology (ADGT)  
**Section:** Molecular Genetics  
**Location:** ["PBS Nanaimo"]  
**Status:** Ongoing  
**Theme:** Climate Vulnerability  
**PSSI Pillar:** 1-Conservation and stewardship  
**Speaker Theme:** Salmon in a changing climate  

**Overview:**  
Pacific salmon are broadly distributed across western Canada and the northern
Pacific Ocean with spawning grounds located over a wide diversity of
freshwater habitats. In general, Pacific salmon return to their natal spawning
grounds to reproduce, and not surprisingly this has resulted in substantial
genetic variation among different salmon populations throughout the Canadian
range. Genetic variants among and within populations of the majority of
Canadian Pacific salmon have been characterized using relatively low numbers
of genetic markers, and this characterization has enabled the development of
the genetic-stock identification and parentage-based tagging programs within
Fisheries and Oceans Canada which provide vital information for management of
fisheries and hatcheries. Despite the utility of these developments, low-
density genetic markers are insufficient to assess adaptive genetic variation
in these species, leaving critical gaps for conserving fitness-associated
genetic diversity and for improving resilience to climate change. Previously,
the costs of next-generation sequencing were prohibitive for assessing genome-
wide genetic variation in species with large genomes such as salmonids.
However, reductions in these costs combined with publication of reference
genome sequences for the Pacific salmonids has opened novel opportunities to
address these gaps. The proposed project will utilize low-coverage whole-
genome resequencing to assess genome-wide patterns of genetic variation among
and within populations of Pacific salmon. These data will feed into several
analyses to identify genomic regions and variation involved in environmental
adaptation, to reassess the genetic support for currently defined conservation
unit boundaries, and to estimate the relative climate change resilience of
different populations of Canadian Pacific salmon. Initially, the proposed
project will focus on Chinook and Sockeye Salmon with a goal of sequencing
individuals from 48 populations of each species distributed across the
species’ range. We will leverage samples currently available in the Molecular
Genetics DNA archives to enable these efforts. In the longer-term, the
objectives of this project will expand these sequencing efforts to increase
the coverage of individuals, populations and species of Pacific salmon. This
expansion of scope will be necessary to fully consider conservation of within
population genetic diversity, and to resolve parallel patterns of genetic
adaptation across Pacific salmon in Canada. The first-year objectives of the
study are: 1) Identify 48 populations representative of the range-wide
diversity of Chinook and Sockeye Salmon. 2) Obtain samples from 18 Chinook
individuals or 8 Sockeye individuals from each identified population from the
Molecular Genetics DNA archives, and extract DNA for each sample. 3) Prepare
the extracted DNA samples for low-coverage whole-genome sequencing, and submit
the samples to an external sequencing service provider. 4) Collect relevant
environmental datasets and climate change projections for the locations and
life histories of the identified populations. 5) Receive sequencing reads for
all submitted DNA samples. The long-term objectives of the study are: 6) Align
sequencing reads from the first year of the study to the Chinook or Sockeye
Salmon reference genomes. 7) Determine allele frequency variation among and
within populations of each species. 8) Analyze genome-wide population
structure in each species and identify outlier regions of genetic
differentiation among populations. 9) Analyze genome-environment associations
to resolve environmental factors underlying genetic differentiation among
populations. 10) Utilize current inter-population genomic variation to
determine “genomic offsets” in the context of climate change projections
(i.e., the extent of genetic change necessary to parallel expected changes in
the environment). 11) Expand sampling and sequencing effort to include Chum,
Pink and Coho Salmon, and to add additional Chinook and Sockeye Salmon
population that address any gaps in the initial analysis. 12) Repeat the
analyses above across species to evaluate cross-species patterns and factors
important to Pacific salmon adaptation in Canada. 13) Report on genome-wide
genetic variation in comparison to existing conservation unit boundaries with
dedicated consideration of putatively adaptive genetic variation. 14) Report
on genetic estimates of relative climate change resilience among different
populations of each Pacific salmon species examined.



[⬅ Back to Home](../index.qmd)
