---
title: "Quantitative assessment of the impact of Smallmouth Bass suppression efforts in Cultus Lake and SMB emigration from Cultus Lake"
---

## 🧬 Project Summary

**Lead(s):** Daniel Doutaz  
**Division:** Stock Assessment and Research (StAR)  
**Section:** Fraser and Interior Area Salmon Stock Assessment  
**Location:** ["Cultus"]  
**Status:** Ongoing  
**Theme:** Threat Assessment and Mitigation  
**PSSI Pillar:** 1-Conservation and stewardship  

**Overview:**  
Smallmouth bass (Micropterus dolomieu), a piscivorous fish species native to
eastern North America, have been introduced into Cultus Lake, British
Columbia. Cultus Lake is home to endangered sockeye salmon (Oncorhynchus
nerka) as well as endemic Cultus pygmy sculpin (Cottus aleuticus). Smallmouth
bass introduced in other salmon-bearing habitat have been observed to exert
substantial mortality on salmon fry and smolts, suggesting a similar impact
may be possible in Cultus Lake. Observations of sockeye salmon, and Cultus
pygmy sculpin in the diet of captured smallmouth bass demonstrates predation
upon two native species at risk. While smallmouth bass represent a threat to
the Cultus Lake native fish community and species at risk specifically, they
are also highly valued by some anglers. Importantly, as a source population,
they also represent a real and present threat to other ecosystems in the Lower
Mainland. Smallmouth bass are often found in streams and rivers; in fact, they
have already been found downstream of Cultus Lake. Additionally, there is the
threat of anglers moving smallmouth bass to other waterbodies in the Lower
Mainland to create new bass fisheries, which themselves would create risk to
receiving environments. While there are largemouth bass (M. salmoides)
populations in various waterbodies throughout the Lower Mainland, this is the
first verified smallmouth bass population, and has drawn a lot of attention
from the angling community. Early work on this population has identified a
divergence of public opinions: some value native species (especially sockeye
salmon) and want to see bass suppressed; other values angling opportunities
for smallmouth bass and will strongly oppose any measures to affect this
valued fishery resource.

There are two issues that this project will address: (1) understanding which
suppression options will result in the lowest opposition from anglers and
community members, thereby identifying the risk of unintended consequences
(e.g., additional transfers to other lakes); and (2) determining the
suppression strategy (combination of different suppression options) which will
best inform estimates of effectiveness for each suppression option so as to
maximize effective suppression moving forward to reduce impacts on sockeye
salmon recruitment.

In year one of this project, an electrofishing boat will be used to capture
smallmouth bass, and all bass will be tagged with passive integrated
transponders (PIT tags). These PIT-tagged fish will help determine the initial
population size (through mark-recapture methods) and provide a baseline for
future smallmouth bass suppression efforts. A subset of smallmouth bass will
also be tagged using acoustic transmitters (n=25; Vemco V9 &amp; V13 acoustic
tags) to track their movements within the Cultus Lake system, and to determine
if any emigration out of the system is occurring.

The smallmouth bass fishery will be monitored to assess total fishing effort
(using standard access point creel survey procedures), harvest rates, harvest
size, and catch rates (total number fish released + harvested). All harvested
bass reported by anglers will be measured, weighted, scanned for PIT tags, and
have scales removed for later aging. Additionally, as part of the catch
monitoring program anglers will be surveyed to determine their level of
satisfaction with their bass catch rates and size, native fish catch rates and
their opinions on the different suppression options considered. These survey
answers will allow for changes in utility and attitudes to be tracked over
time.

Lastly, nest destruction and removal of male bass guarding nests is to occur
once spawning begins in the spring. Bass activity in the spring should be
monitored frequently to identify the start of spawning season. Once nests are
constructed, a survey of known spawning locations should occur to identify
nests for destruction. Captured males will be measured, weighed, have sex and
maturity status confirmed, scanned for PIT tags, and have scales and/or
otoliths removed for aging.

This project was developed in partnership between Simon Fraser University, the
Province of BC, and the DFO. Please see the attached &quot;Cultus Lake Smallmouth
Bass Suppression Plan.pdf&quot; in the &quot;Supporting Resources&quot; section for
additional information on subsequent years of this project.



[⬅ Back to Home](../index.qmd)
