---
title: "Innovative Ecosystem Based Approaches to identify cumulative stressors: Salmon Fit-Chips and eDNA"
description: "Salmon experience a variety of physiological stressors and pathogens over migration which can be monitored non-lethally using Fit-Chip technology. Chinook salmon will expose themselves to potentially impactful stressors to avail feeding opportunities, enhancing vulnerability to cumulative stressors. eDNA data resolves habitat usage for Chinook salmon and demonstrating they associate with high biomass areas (prey availability), including aquaculture facilities, and avoid harmful algae. Models addressing the cumulative and synergistic interplay between factors will inform which levers under human control will result in strongest outcomes for salmon."
author: "Kristi Miller-Saunders"
toc: true
---

## 📋 Project Summary

**Lead(s):** Kristi Miller-Saunders  
**Division:** Aquatic Diagnostics, Genomics and Technology (ADGT)  
**Section:** Molecular Genetics  
**PSSI Pillar:** 1-Conservation and stewardship  
**Speaker Theme:** Follow the Fish: Life Cycle Monitoring of WCVI Chinook  
**Presentation:** December 03, 2025 at 05:00 AM  

**Overview:**  
Salmon experience a variety of physiological stressors and pathogens over migration which can be monitored non-lethally using Fit-Chip technology. Chinook salmon will expose themselves to potentially impactful stressors to avail feeding opportunities, enhancing vulnerability to cumulative stressors. eDNA data resolves habitat usage for Chinook salmon and demonstrating they associate with high biomass areas (prey availability), including aquaculture facilities, and avoid harmful algae. Models addressing the cumulative and synergistic interplay between factors will inform which levers under human control will result in strongest outcomes for salmon.   

**Activities:**  
Preliminary Fit-Chip analysis of WCVI microtroll and purse seine caught juvenile Chinook salmon (project years 2023-2024) suggests several factors that may be limiting the health and survival of early marine Chinook salmon, most notably: high water temperature, hypoxia stress, harmful algae and infectious agents . In 2025-2026 we will target these factors for detailed spatiotemporal analysis and conduct analyses connecting Fit-Chip and eDNA data as described in the following objectives:

1. Fit-Chip analysis of microtroll collected Chinook indicated a much higher prevalence of hypoxia stress in the wild than anticipated based on the laboratory challenge studies where extremely low levels of oxygen were required to elicit a stress response. Initial results indicate that hypoxia signals were strong at inlet heads where previous oceanographic studies have identified low oxygen levels in corresponding seasons. Spatio-temporal models, an early version of which identified the aforementioned signal, will be further developed to include other potential sources of hypoxia stress, including gill pathogens and harmful algal blooms (HABs), the presence of which can be determined by eDNA. We are collaborating with DFO specialists working on HABs in WCVI to build a multifactorial model (Andrew Ross et al.).

2. Prevalence and infection density of Tenacibaculum maritimum in Fit-Chip data from purse seine collected Chinook salmon exceeded levels previously observed in any field study (molecular or otherwise) of wild salmonids (close to 100% prevalence on some sampling days). This bacterium has been found to cause rapid mortality in salmonids and has been negatively associated with population-level survival in BC Chinook salmon. It is a common cause of salmon health events in BC netpen aquaculture and is elevated in the water around active pens. We observed T. maritimum detections in more northerly sounds sampled in the fall, coincident with detections in eDNA associated with aquaculture. An ongoing sequence-based epidemiology study will determine whether T. maritimum strains vary between sounds or there is some level of connectivity between sounds. We will also conduct statistical analyses to check for associations between T. maritimum and the many physiological, morphological, and clinical variables in our dataset. Additionally, we may be able to compare T. maritimum levels to CPUE data (or perhaps acoustic monitoring data). For this infectious agent, and other high ranking pathogens run on Fit-Chips, we will check for correlations with corresponding eDNA measurements and the aforementioned metrics of fish health. Another agent, Paranucleospora theridion, which has previously demonstrated associations with aquaculture and sea lice, appeared at much higher frequency in Clayoquot Sound relative to other inlets. Like T. maritimum, P. theridion was statistically associated with Atlantic salmon detections in eDNA samples. We will employ multiple statistical approaches to test for a relationship between this pathogen and aquaculture, including models of infestation pressure and distance to active netpens. The same approach could be applied to other agents where a biological mechanism is expected. Agents of particular interest are Atlantic salmon calicivirus, Cutthroat trout virus-2, Tenacibaculum dicentrarchi, Tenacibaculum finmarkense,  and Piscirickettsia salmonis, all of which were positively associated with Atlantic salmon eDNA detections and thus aquaculture.

3. MGL has recently developed a starvation panel for use on the Fit-Chip that determines when fish present gene expression signals indicating food deprivation. As starvation was a primary hypothesized driver coming out of the WCVI Chinook marine risk assessment process, we will apply this new panel on select samples to identify spatio-temporal patterns in starvation. We will compare Fit-Chip starvation data to stomach sample analysis (Bokvist et al.), eDNA data characterizing salmon prey distribution (Gauthier et al.), and plankton data (Sastri et al.). Together, this data should allow us to identify spatiotemporal hotspots of good and poor dietary conditions for juvenile salmon.   

4. While thermal stress was not detected in microtroll samples collected from October through May across years (as expected), there was a strong thermal stress signal detected in Barkley purse seine collected Chinook in 2022 (as hypothesized during the WCVI Chinook risk assessment process). 2023 and 2024 purse seine samples will be run on Fit-Chips to determine whether this pattern is consistent across years. In order to understand potential impacts to wild stocks, additional sampling of fish and eDNA from more northerly sounds (i.e. Nootka and Kyuquot) during July and August would be beneficial in 2025. Statistical analyses will be conducted to identify other stressors, including pathogens, that are associated with exposure to high water temperatures (HWT). Through the use of eDNA data, this analysis will also explore how salmon ecosystems change with increasing SST in order to inform changing ecosystem dynamics under climate change

5. Next to the above mentioned observations, eDNA analysis was able to provide coarse spatiotemporal distribution patterns for all pacific salmon, as well as cutthroat trout, steelhead and Dolly Varden, that largely agreed with the spatiotemporal distribution of salmonids from microtrolling data. In total, eDNA metabarcoding was able to identifying 1146 operational taxonomic units (OTUs) from viruses and bacteria, algae, zooplankton, nekton, salmonids, to marine mammals including whales, highlighting the complexity and diversity of the marine ecosystems of WCVI. Preliminary network analysis indicates ecosystem wide changes associated with aquaculture, as Atlantic salmon detections correlated with the presence of several HABs, microorganisms like amoebas, algae, cnidarians, bryozoans and numerous benthic polychaetes. This could potentially be related to nutrient loading by aquaculture., a hypothesis we will investigate in 2025/2026. Strikingly, aquaculture was also associated with forage fish and predators, including steelhead, coho, Dolly Varden, cutthroat, and Chinook, suggesting that salmonids with extended coastal life histories are attracted to high biomass areas such as aquaculture sites.  Chinook showed a strong aversion to HABs that were not associated with aquaculture, but no such relationship was observed with aquaculture associated HABs. In 2025/2026 we will investigate whether Chinook risk exposure to HABs in order to avail themselves of the feeding opportunities associated with aquaculture facilities. For 2025-2026, we will shift our focus into continued sampling of Barkley, Nootka, and Kyuquot Sounds in order to be able to compare northern and southern Sounds with different oceanographic features and anthropogenic impacts. Analysis will focus on detailed spatiotemporal breakdown of shifts in habitat usage by Chinook and the underlying changes in ecosystem composition in an attempt to identify the drivers of fish health events identified by Fit-Chips. 

6. It is expected that in the third year of PSSI, stock assessment will provide an additional modeler to work collaboratively with Bass, Llewellyn, Deeg, and possibly others to build the most comprehensive, data-driven modeling to address the cumulative and synergistic interplay between key factors undermining salmon condition and survival identified in the WCVI Chinook Marine Risk Assessments, including prey availability, environmental stress (climate and anthropogenic), pathogens, toxicants/harmful algae, predators, competition, and freshwater carryover effects.

[⬅ Back to Home](../index.qmd)
