---
title: "Relative reproductive success of hatchery- versus natural-origin salmon in Canadian integrated populations"
---

## 🧬 Project Summary

**Lead(s):** Eric Rondeau, Tim Healy, Kyle Wellband  
**Division:** Aquatic Diagnostics, Genomics and Technology (ADGT)  
**Section:** Molecular Genetics  
**Location:** ["Sarita River"]  
**Status:** Ongoing  
**Theme:** Hatchery Science  
**PSSI Pillar:** 2-Salmon enhancement  
**Speaker Theme:** Hatchery science  

**Overview:**  
Enhancement of Pacific salmon through hatchery production is a key component
of supporting wild salmon populations. Objectives of hatchery enhancement span
conserving at-risk stocks, rebuilding lower abundance stocks, providing
harvest opportunities and increasing public awareness through outreach and
education. However, there are also risks associated with hatchery enhancement;
differences between a hatchery and a natural habitat affect both the genetic
and environmental factors that shape the performance and fitness of salmon.
Consequently, hatchery-origin salmon may be less suited to wild habitats than
their natural-origin counterparts, and the presence of hatchery-origin fish on
a natural spawning ground may reduce the fitness of a population overall. The
relative fitness of hatchery-origin compared to natural-origin salmon has been
estimated in a handful of systems through determination of relative
reproductive success (RRS). In these studies, returning adults are assigned
back to their parents using genetic tags called parentage-based tags, and RRS
is inferred by the number of returns per family from hatchery-origin compared
to natural-origin parents. In general, the results of RRS studies suggest that
hatchery-origin fish have lower natural reproductive success than natural-
origin fish, and this reduced RRS is potentially transferred across
generations. Despite this pattern, the extent to which hatchery-origin fitness
is lower than natural-origin fitness is likely dependent on current and
historical factors impacting specific systems, including hatchery practices.
To date, no study has estimated the RRS of hatchery- and natural-origin
Pacific salmonids in integrated populations enhanced by the Fisheries and
Oceans Canada Salmonid Enhancement Program (SEP). This is a critical knowledge
gap for effectively managing hatchery production, as genetic management of
these systems currently assumes a RRS of 0.8. This value is a reasonable
consensus value from published estimates in USA rivers, but the SEP has had
clear guidelines for genetic management since at least the 1980s, and it is
possible that RRS estimates from USA hatcheries are inaccurate for SEP
hatcheries. Utilization of an inaccurate RRS estimate could result in
mismanagement of genetic risks associated with hatchery production, because
the number of hatchery-origin fish that are predicted to utilize the natural
spawning grounds increases as RRS increases, whereas a high RRS infers
relatively low negative consequences for fitness associated with hatchery-
origin spawners. Therefore, accurate estimation of RRS is important for
effective genetic management of SEP hatcheries, particularly in the context of
managing the influences of the hatchery and natural environments on the
adaptive trajectories of integrated populations (i.e., proportionate natural
influence or “PNI”). The first-year objectives of the study are: 1) Initiate
extensive genetic sampling of both the escapement and broodstock for at least
one Pacific salmon population enhanced by the SEP (confirmed population:
Sarita River Chinook Salmon). 2) Use a genetic biomarker panel to genotype
these natural-origin and hatchery-origin parents. 3) Explore alternative
approaches to enable widespread RRS estimation across SEP hatcheries even in
systems where extensively escapement sampling is infeasible. The long-term
objectives of the study are: 4) Explore options to increase sampling efforts
to approach comprehensive escapement sampling in future years. 5) Continue
these genetic sampling efforts to derive parentage-based tags for returning
adults from both hatchery-origin and natural-origin production. 6) Estimate
RRS in SEP hatcheries to allow improved management of genetic risks associated
with hatchery influences.



[⬅ Back to Home](../index.qmd)
