---
title: "Genetic associations with age of return in male Canadian Chinook Salmon"
---

## 🧬 Project Summary

**Lead(s):** Eric Rondeau, Tim Healy, Kyle Wellband  
**Division:** Aquatic Diagnostics, Genomics and Technology (ADGT)  
**Section:** Molecular Genetics  
**Location:** ["Chilliwack River","Puntledge River","Qualicum River"]  
**Status:** Ongoing  
**Theme:** Innovation & Diagnostics  
**PSSI Pillar:** 2-Salmon enhancement  
**Speaker Theme:** Genetics and adaptation  

**Overview:**  
Chinook Salmon display arguably the widest range of life history strategies of
all Pacific salmonids. One important life history strategy in male Chinooks is
to return after one fewer year in the marine environment than the earliest
returning females. These early-returning males or “jacks” are relatively
small, and participate in spawning by employing an opportunistic “sneaker”
strategy to fertilize small numbers of eggs from many spawning events
involving females and larger, more dominant, males. In general, spawning
success in Chinook Salmon is closely related to size; however, jacks
experience the risk marine predation for at least one less year than other
males, and the success of jacks is a product of negative frequency-dependent
selection. In other words, as the proportion of large males increases, the
relative success of jacks increases, whereas as the proportion of jacks
increases, the relative success of jacks decreases. In addition, from an
evolutionary perspective jack males represent an important natural avenue of
gene flow between different spawning years in Pacific salmon species.
Therefore, the natural occurrence of low frequencies of jack males in Chinook
Salmon populations is likely beneficial for the population and species as a
whole. There are both genetic and environmental factors that contribute to the
tendency of a male Chinook to return as a jack, and current understanding
suggests that growth rates at early life stages combined with size-at-age
thresholds play key roles in the likelihood of observing the jack phenotype
later in life. These factors suggest that hatchery enhancement may
artificially raise the proportion of jack males in a population, and this has
been observed in some hatchery lines. Despite the importance of the jack life
history strategy overall, there is no doubt that larger Chinook males are more
successful on the spawning grounds, and larger salmon are more valuable to
fisheries. Consequently, there are concerns that hatchery enhancement may
shift the distribution of ages of return towards younger age classes with
negative consequences for both harvest and population-level fitness. To
mitigate the risk of shifting a population’s average age of return, hatcheries
may manage jacks in broodstock differently than other males by preferentially
retaining older males. The jack phenotype is known to be inherited to a
reasonable extent, and thus this broodstock screening should counter the
likelihood of overrepresentation of jack fathers in hatchery-origin offspring.
However, as genetic and environmental factors impact the tendency to jack,
broodstock management would be improved and facilitated if jacks among the
potential brood could be screened specifically for the genetic factors
underlying the jack phenotype; these factors are the most likely to directly
impact the proportion of jacks in the subsequent generation of hatchery-origin
offspring. Recent research has shown that specific y-chromosome haplotypes are
strongly associated with the tendency of a male to return as a jack, but these
haplotypes are unique to different regions. Y-chromosome haplotypes in
Canadian Chinook Salmon have not be characterized in the context of ages of
return for any population, impairing the ability to develop genetic tools to
refine hatchery broodstock management. Therefore, resolving the genetic
variants responsible for known inheritance of the jack life history strategy
is an important step in improving genetic hatchery management in the Fisheries
and Oceans Canada Salmonid Enhancement Program (SEP). The first-year
objectives of the study are: 1) Identify males of known age classes from
previously genotyped broodstock from three Chinook populations enhanced by SEP
(confirmed populations: Chilliwack River Fall, Puntledge River Fall and
Qualicum River). 2) Perform reduced-representation sequencing on 256 males
from each population across age classes with approximately 80 jacks per
population. 3) Analyze genotype-phenotype associations between genetic
variants and the age of return among individuals, including a specific
analysis of y-chromosome haplotypes. The long-term objectives of the study
are: 4) Expand these analyses to include additional SEP-enhanced Chinook
populations from other regions to confirm the generality of genetic
associations. 5) Design genetic tools to allow rapid screening of genetic
variants that have large effects on the tendency of a male Chinook to return
as a jack. 6) Potentially expand these analyses to examine genetic
associations with age of return in female Chinook, which would also support
genetic management of SEP broodstocks.



[⬅ Back to Home](../index.qmd)
