---
title: "Kim Hyatt’s Legacy Data: Juvenile Sockeye Biosample Data and Summary Metrics for B.C. Study Lakes, 1977-present"
description: "No description available."
author: "Athena Ogden, Patrick Thompson, Michelle Charbonneau"
keywords: ["salmon science", "Unspecified", "Uncategorized", "Ecosystem Sciences (ESD)", "Regional Ecosystems Effects on Fish and Fisheries"]
---

## 🧬 Project Summary

**Lead(s):** Athena Ogden, Patrick Thompson, Michelle Charbonneau  
**Division:** Ecosystem Sciences (ESD)  
**Section:** Regional Ecosystems Effects on Fish and Fisheries  
**PSSI Pillar:** Unspecified  
**Speaker Theme:** Uncategorized  

**Overview:**  
No description available.   

**Activities:**  
This part of an ongoing effort to capture, catalog, assess and make accessible, as appropriate, the volumes of paper notes, intellectual property,  digital and  physical copies of data generated by or otherwise linked to Dr. Kim Hyatt; these data have been inaccessible since his passing and require a knowledgeable party to carry out the data rescue.

In FY 2024/25,  funds requested will be used to rescue orphaned data related to the following species, stock, life stage and geographic region: 

i)	Geographic Area: West Coast of Vancouver Island (e.g., Hobiton, Cheewhat, Muriel lakes); Central Coast (e.g., Long, Owikeno lakes), North Coast (e.g., Meziadin, Babine lakes), Transboundary (e.g., Tahltan, Tuya, Okanagan lakes).
ii)	Species: Sockeye Salmon
iii)	Salmon Management Unit/Conservation Unit: multiple Conservation Units and Management Units
iv)	Life Stage: Juvenile (freshwater) Sockeye: primarily parr, pre-smolt, and smolt life stages

This data rescue will further develop and populate a data base hosted and maintained by Local Biological Consultants, familiar with Dr. Kim Hyatt's work. The data rescue will bring the physical repository of Dr. Hyatt's work into a workable and shareable format. The database being maintained is searchable and uses optical character recognition (OCR) to rescue data without having to open and read each scanned or digitally retrieved file. Where OCR cannot assess hand written notes, the original scan is kept. We anticipate the remaining work can be scanned, assessed and appropriately catalogued in the data base for $30,000.

The resulting data products include a user-friendly, menu-driven, forms-based MS-Access relational database, with built-in queries for annual summary reports and export to other programs. If desired, we could make the data available on the Open Data Portal as well.

[⬅ Back to Home](../index.qmd)
