---
title: "Improved understanding of cumulative impacts on salmon survival across freshwater life-stages; tools and approaches for mechanistic assessments"
---

## 🧬 Project Summary

**Lead(s):** David Patterson, Douglas Braun  
**Division:** Ecosystem Sciences (ESD)  
**Section:** Freshwater Ecosystems  
**Location:** ["Thompson"]  
**Status:** Ongoing  
**Theme:** Threat Assessment and Mitigation  
**PSSI Pillar:** 1-Conservation and stewardship  

**Overview:**  
Context: Landscape level assessments of stressors on aquatic habitats, climate
change projections, and population dynamics models can provide cautionary
flags that identify potentially stressed or vulnerable watersheds and/or
populations (e.g., RPA status assessment, Pacific Salmon Explorer). These
approaches are useful for initial watershed or population prioritization.
However, in most cases these approaches are limited in their ability to
accurately describe the cumulative impact that multiple stressors can have on
individuals and specific populations because they lack a mechanistic approach
that can verify the complex interacting pathways of effects on fish (Peacock,
Braun, Hodgson et al., 2023). This complexity makes it difficult to understand
how future landscape alterations and climate change will affect salmon in a
given watershed; thus limiting our ability to provide specific advice to
managers on how to predict which mitigation or recovery actions (e.g. habitat
restoration, harvest reductions) will most effectively recover salmon
populations. We propose to link in situ ecophysiology information with other
biophysical habitat monitoring data to develop mechanistic relationships that
address management issues around habitat-population modeling, assessment of
restoration function, and fish responses to climate change. The specific
management questions are: Q1) What multi-factor stressors limit stage specific
freshwater habitat distribution? Q2) What are the key drivers of stage-
specific survival and growth for life-cycle modelling? Q3) What is the role of
temperature in combination with other key factors in predicting climate change
impacts on salmon growth and survival in a given habitat (e.g. lake, river,
wetlands)? Q4) What are major habitat factors that affect salmon growth and
survival to consider in planning and assessment of habitat mitigation,
restoration, and offsetting effectiveness? The proposal is to execute a series
of projects that directly address these management questions through two main
outcomes 1) improved understanding of cumulative effects, and co-development
of 2) tools and approaches to guide future mechanistic assessments of
cumulative impacts. Improve Understanding: For year 1 &amp; 2, we propose to
continue work on cumulative impact projects: 1) development of in situ stage
specific mechanistic relationships among biophysical factors (dissolved oxygen
(DO), temperature, flow, conspecific competition), distribution, physiological
condition metrics, growth, and survival for juvenile salmonids – all measure
in situ, 2) continue to develop and evaluate ecophysiology tools related to
evaluating fish condition. Life-stage specific mechanistic relationships will
be examined using samples in-hand from three large scale field programs
(Lakes, E-Watch, North Thompson Salmon Ecosystem Program) within the
Freshwater Ecosystems Section. All three programs generate unique multi-year
population data on multiple biophysical factors influencing juvenile salmon
condition, growth, and survival such as, water quality, conspecific density,
temperature, food availability, primary productivity, DO and water level in
lakes, wetlands, and flows in rivers. Models examining the effects of multiple
biophysical factors on condition will be used to understand how interacting
biophysical drivers (including stressors) shape fish condition, while models
examining relationships between condition metrics and growth and/or survival
will examine the use of condition metrics as tools to indicate future salmon
presence, growth and survival. Concomitant lab work is ongoing to support the
development of ecophysiology tools, such as growth hormones (IgF) for
freshwater salmon growth, troponin for oxygen stress, and triglycerides (TAG)
for nutritional status, that can be used as potential indicators of habitat
quality. For Year 3&amp;4 we will use the results from year 1&amp;2 to identify and
test key knowledge gaps on cumulative effects in salmon (e.g. Iacarella
proposal). This selection of multifactor field experiments could include: low
DO and high temperature; food availability, temperature, and growth/survival;
pH and temperature tolerance experiments with preference/avoidance behaviour
studies; and temperature and migratory stressors on in-river survival
Sockeye/Chinook/Coho. This project is distinct from related PSSI proposals in
that we are proposing a mechanistic approach to test the cumulative impact of
multiple factors directly on individual fish response (i.e. growth, survival,
stress) in their native habitats, leveraging multiple program expertise both
within the freshwater section and beyond. Our experience is that science
advice to major management decisions are best supported by a mechanistic
understanding how environmental and physiological processes directly impact
fish themselves. This is foundational work that can then be used to generate
population responses were appropriate. However, we acknowledge that not all
management questions to science require such an in-depth experimental
approach, which is why we are proposing the guideline development to help
managers and researchers prioritize how best to approach assessing cumulative
impacts, as well as work with the other related projects. The proposal is
complementary to other PSSI science proposals in that we are addressing
similar questions, but at different spatial scales (e.g. Iacarella’s broad
region-wide scale) and biological levels of organization. The work also
complements broad-scale modeled predictions of discharge, temperature, and DO,
that can be used with our mechanistic relationships to generate robust
predictions of fish responses to climate change. More specifically, we will
help test some of key stressor interactions that emerge as pervasive across
the province from Iacarells’s proposal with field-based studies. We will
directly link the outputs from Naman’s model of habitat suitability with
direct measures of fish condition, fish performance and survival (i.e. a form
of cross validation). We will work with Czembor’s group to share ideas on the
state of knowledge of key limiting factors, and evaluate fit-chips as a
potential ecophysiological tool from the Miller proposal. Tools and
Approaches: We will synthesize approaches and our results to develop a
pragmatic guide for initiating mechanistic cumulative effects investigations.
We started with a literature review (Y1-2) of current methods for assessing
physiological condition, as an integrated measure of habitat quality. The
review will examine the benefits and limitations of these different
physiological condition metrics and span metrics that include genomic,
transcriptomic (fitchips), proteins (e.g. hormones, enzymes), metabolites
(TAGs, ions), and phenotypes (size). This verification of physiological tools
will be done in conjunction with assessing different habitat monitoring and
modelling approaches (e.g. Cunningham 2022; Naman proposal) to verify Value of
Information. For Year 3 &amp; 4\. The culmination of the literature review and
field/lab projects will be a pragmatic guide for a tiered approach (i.e.
opinions, reviews, observations, hypothesis testing, quantification of
uncertainty) to initiate mechanistic cumulative effects investigations that
directly link to management advice (Patterson et al. 2016). The guide can be
used to develop in-depth monitoring programs where watersheds or populations
are flagged by broad scale analyses as stressed or at risk (Iacarella
proposal).



[⬅ Back to Home](../index.qmd)
