---
title: "Characterizing and monitoring priority contaminants of concern in WCVI juvenile salmon"
---

## 🧬 Project Summary

**Lead(s):** Lisa Loseto  
**Division:** Ocean Sciences (OSD)  
**Section:** Ecology and Biogeochemistry  
**Location:** N/A  
**Status:** Ongoing  
**Theme:** Threat Assessment and Mitigation  
**PSSI Pillar:** 1-Conservation and stewardship  
**Speaker Theme:** Marine ecosystems and stressors  

**Overview:**  
The work proposed here is focused on the contaminant component of the “Follow
the Fish” program (FtF), which also a PSSI project proposal focused on West
Coast Vancouver Island (WCVI) Chinook salmon. The overall aim of the work
described here is to characterize and rank contaminants of concern in WCVI
juvenile Chinook salmon and assess contaminant-related health effects in WCVI
juvenile Chinook salmon deemed to be of highest concern.

A recent contaminant assessment of six priority contaminant classes in 11
adult Chinook stocks revealed that WCVI Chinook had among the highest
concentrations of the following contaminants: alkylphenols (APs), chlorinated
paraffins (CPs), and two organochlorine pesticides (HCH, and DDT). The goal of
the proposed project is to build on these findings by analyzing an additional
suite of contaminants in WCVI juvenile salmon, with a particular focus on
juvenile Chinook, in order to support a prioritization and ranking of
contaminants of concern. This project will also deliver new data on WCVI
Chinook habitat by analysing sediments and water to inform local land use
practices and possible mitigation steps. Results will be compared to our
contaminant characterization and prioritization that is underway in juvenile
and adult Fraser River Chinook. This study will provide enabling information
to PSSI and fisheries managers as they aim to curb historic declines in
priority Pacific salmon stocks and enable their recovery.



[⬅ Back to Home](../index.qmd)
