---
title: "Explanation for the Collapse of the Commercial Chum Salmon Fishery in British Columbia"
---

## 🧬 Project Summary

**Lead(s):** Chrys Neville  
**Division:** Ecosystem Sciences (ESD)  
**Section:** Regional Ecosystems Effects on Fish and Fisheries  
**Location:** N/A  
**Status:** Not funded  
**Theme:** Unspecified  
**PSSI Pillar:** Unspecified  

**Overview:**  
The commercial chum fishery in British Columbia has collapsed. The fishery,
that averaged about 15,000 t between 1950-1989, declined sharply since 2010
and in 2022 was only 180 t. The catch in 2023 appears to be as low or lower.
In addition to the collapse of the fishery, there is a collapse of
escapements. Atlas et al (2022) reported an 80-90% collapse in spawning chum
salmon abundance in Central Coast rivers since 1960. The Fraser River,
historically the largest producer of Chum salmon in BC, may not reach targeted
escapement for 2023 despite not allowing any fishing. Additionally, targeted
chum escapements for numerous other rivers flowing into the Strait of Georgia
appear to be alarmingly low in 2023. These declines in chum salmon are as
equally, or even more alarming, as the collapse of southern BC coho salmon
escapements in the 1990s that resulted in the closure of key fisheries. The
dramatic declines of chum salmon have not only impacted commercial fisheries,
historically the most important salmon fishery by weight in BC, but declines
have significant implications to First Nations. Additionally, Hanson et al
(2001) demonstrated that chum salmon were 2 to 3 times more important in the
diet than Chinook salmon during the fall and early winter for “southern
resident killer whales” adding an additional concern for the protection of
southern resident killer whales.

The reasons for the declines in chum salmon are not understood and not
studied. We have 25 years of juvenile chum catches in the Strait of Georgia
and three years of catches of British Columbia chum salmon in the winter in
the Gulf of Alaska that we can use to develop hypotheses to explain why
declines are occurring and what might be done to manage existing populations
to maximize future production as ocean ecosystems change.

There is no trend in the catches of juvenile chum salmon in the juvenile
salmon surveys conducted by the Salmon Marine Interactions Program in the
Strait of Georgia for the past 25 years indicating that the number of
juveniles entering the ocean has not declined. However, there has been no
stock specific DNA analysis completed for the juvenile chum salmon catches in
these surveys in the Strait of Georgia because funds were not available.
Surveys in the Gulf of Alaska in the winter of 2019, 2020 and 2020 were the
first studies of Canadian chum salmon during the winter. DNA and age analysis
indicated that although Canadian chum salmon in their first winter in the
ocean were encountered, there were very few Canadian chum salmon in their 2nd,
3rd or 4th winters. However, these older age classes were encountered for chum
salmon that originated from Alaska, Russia and Japan. Therefore, results from
the winter expeditions and results from the juvenile salmon surveys suggest
that recent declines occur before or about the time of the first ocean winter.

This project will produce stock specific juvenile abundances of chum salmon in
the summer and fall survey catches in the Strait of Georgia. These abundances
will be used to determine if there are stock specific trends in abundance over
the 25 years of sampling or stock specific patterns of juveniles remaining in
the Strait of Georgia through their first marine summer. The stock specific
abundances will also be compared to the stock composition of chum in the
catches from our winter surveys in the Gulf of Alaska. Resulting relationships
with survey abundance trends, escapements, hatchery production, stock specific
growth and condition will be used to develop hypotheses for possible causes of
the decline in ocean survival of BC chum salmon and what can be done to
maximize survival in the future of changing ocean ecosystems.

Literature cited:  
Atlas, W.I., K.L. Wilson, C.K. Whitney, J.E. Moddy, C.N. Service, M. Reid, and
M. R. Sloat. 2022. Quantifying regional patterns of collapse in British
Columbia central coast chum salmon (Oncorhynchus keta) populations since 1960.
Can. J. Fish. Aquat. Sci. 79: 2072-2086. Hanson MB, Emmons CK, Ford MJ,
Everett M, Parsons K, Park LK, Hempelmann J, Van Doornik DM, Schorr GS,
Jacobsen JK, Sears MF, Sears MS, Sneva JG, Baird RW, Barre L. Endangered
predators and endangered prey: Seasonal diet of Southern Resident killer
whales. PLoS One. 2021 Mar 3;16(3):e0247031. doi:
10.1371/journal.pone.0247031. PMID: 33657188; PMCID: PMC7928517.



[⬅ Back to Home](../index.qmd)
