---
title: "Understanding the impact of Arctic outflow winds on British Columbia fjords."
---

## 🧬 Project Summary

**Lead(s):** Jennifer Jackson  
**Division:** Ocean Sciences (OSD)  
**Section:** Ecology and Biogeochemistry  
**Location:** ["Mainland Inlets"]  
**Status:** New  
**Theme:** Unspecified  
**PSSI Pillar:** 1-Conservation and stewardship  
**Speaker Theme:** Marine ecosystems and stressors  

**Overview:**  
There are times during most winters that Arctic air masses settle over the
British Columbia (BC) interior east of the coast mountain range. Some of this
cold air is transported to the coast as an outflow wind via coast mountain
valleys. In Bute Inlet, it has been shown that these outflow winds can cool
the upper 100 m up to 1.9°C and gain up to 4.1 mLL -1 of oxygen (Jackson et
al., 2023). Colder, more oxygenated waters can persist for up to 1 year in
Bute Inlet after the outflow event, which could create a marine refugia. To
understand whether this process impacts other fjord systems, a PhD student
(Ehsan Tighizadeh) who is jointly situated int he Natural Resources and
Environmental Studies Graduate Program at the University of Northern British
Columbia and Fisheries and Oceans Canada will expand this study to cover the
entire British Columbia coast. Specifically, they will reconstruct the
historical climatology of Arctic outflow winds and their impact on fjord
waters along the BC coast. Through this work, it is anticipated that other
marine refugia created by Arctic outflow winds will be identified.



[⬅ Back to Home](../index.qmd)
