---
title: "Climate Downscaling for salmon conservation in Marine Ecosystems"
---

## 🧬 Project Summary

**Lead(s):** Di Wan, James Christian  
**Division:** Ocean Sciences (OSD)  
**Section:** Ocean Modelling and Prediction  
**Location:** N/A  
**Status:** Ongoing  
**Theme:** Climate Vulnerability  
**PSSI Pillar:** 1-Conservation and stewardship  

**Overview:**  
The ocean environment determines year-to-year fluctuations in salmon
productivity and is changing rapidly due to anthropogenic climate change.
Oceanographers in DFO and other departments such as ECCC have collaborated in
the development of ocean models that can be used to assess future changes in
the environment for salmon and other fish species. However, there is a
significant &#39;scale gap&#39; between the global, coarse resolution Earth System
Models used to generate climate projections and the high-resolution (e.g., 3
km) models used to downscale these projections for coastal and shelf
environments. This gap can be filled by basin-scale models at 1/12 to 1/4
degree. The present research plans to build on existing efforts funded under
CSRF to conduct simulations of projected future climates at these intermediate
scales. In this way we will create an &#39;envelope of possibilities&#39; of future
environments for salmon in the oceanic environment.

The main anticipated outcomes from this work are (1) development of a capacity
to downscale climate projections at intermediate scale, including
biogeochemistry (e.g., oxygen concentration), and (2) generation of data
products that can used for Species Distribution Modelling of salmon in the
oceanic environment.



[⬅ Back to Home](../index.qmd)
