---
title: "Climate Change Vulnerability Assessments"
---

## 🧬 Project Summary

**Lead(s):** Sue Grant  
**Division:** Ecosystem Sciences (ESD)  
**Section:** Regional Ecosystems Effects on Fish and Fisheries  
**Location:** N/A  
**Status:** New  
**Theme:** Unspecified  
**PSSI Pillar:** Unspecified  
**Speaker Theme:** Uncategorized  

**Overview:**  
(details provided in attached proposal submitted to CSRF in 2022-2023; and
PSSI Science 2023-2024) DFO managers urgently require information concerning
which salmon species or populations are most resilient to climate change.
These data are critical for managers to best allocate limited resources,
focusing recovery efforts on salmon populations best aligned with future
salmon production and diversity. Climate change already affects Canadian
Pacific salmon and their ecosystems, with impacts expected to accelerate.

Climate change vulnerability assessments (CCVAs) are important tools to
support management decisions, providing summaries of the relative threat level
for a population from climate change. These assessments integrate expert
knowledge on salmon, their ecosystems, and climate change projections, and
have been successfully applied to U.S. Pacific salmon populations, but are
currently lacking for Canadian Pacific salmon.

We will apply the U.S. CCVA framework to Canadian Pacific salmon. These
assessments will be conducted for two groups of salmon populations to provide
a toolkit for conducting salmon CCVA’s for the 377 Conservation Units (CUs) of
salmon DFO manages across all five species (Sockeye, Chinook, Coho, Pink and
Chum). These two case studies will include CUs with the greatest risk of
extinction, since these CUs will urgently require climate vulnerability
information to support management decisions.



[⬅ Back to Home](../index.qmd)
