---
title: "Assessing Salinity Alteration of Nursery Conditions for Salmon Smolts following Construction of Roberts Bank Terminal-2"
---

## 🧬 Project Summary

**Lead(s):** Terri Sutherland  
**Division:** Ecosystem Sciences (ESD)  
**Section:** Nearshore Ecosystems  
**Location:** N/A  
**Status:** New  
**Theme:** Unspecified  
**PSSI Pillar:** Unspecified  

**Overview:**  
Millions of Fraser River salmon rely on Roberts Bank tidal flats for food,
shelter, and salinity acclimatization before they undergo a multi-year
migration across the Pacific Ocean for many years. Since harpacticoids provide
a link between primary production (benthic diatom biofilms) and tertiary
production at higher trophic levels (salmon-smolts, sandpipers), harpacticoids
can transfer diatom-derived a high-quality food consisting of long-chain
polysaccharide unsaturated fatty-acids (LC-PUFAs) that serve as a high-quality
migration fuel for salmon smolts. However, modelling scenarios of salinity
estimates on Roberts Bank shows a salinity regime shift towards freshwater 34%
relative to that of the existing tidal flats conditions between pre- and post-
construction of Roberts Bank Terminal-2 (RBT2). On Roberts Bank, the alignment
of diatom-harpacticoid-salmon trophic levels and transfer of LC-PUFAs across
trophic levels must be sustained to avoid a potential “match–mismatch”
scenario (McKinnell and Irvine, 2021). This timely pairing of predator and
prey is also crucial for 1.5 million Western sandpipers (Caldris mauri), that
migrate between Panama to Alaska annually (April 15 – May 15) and stopover on
Roberts Bank tidal flats. Western sandpipers also rely on diatom biofilms (LC-
PUFAs) for fuel for the long migration to Alaska (Warnock and Bishop, 1998;
Elner et al, 2005; Kuwae et al. 2008; Mathot et al. 2010). Given the overlap
of 1) migration stopover location and timing for both salmon and sandpipers on
Roberts Bank; and 2) similar prey preferences (benthic diatom biofilms) and
required LC-PUFAs for migration fuel, a competitive interaction may occur
under these circumstances, leading to a match-mismatch scenario for both
benthic diatom predators. Furthermore, the predicted reduction of salinity due
to RBT2 construction during the season of freshet and migration stopovers of
both salmon and sandpiper, may apply a significant environmental stressor to
this competition for high-quality food.



[⬅ Back to Home](../index.qmd)
