---
title: "Establishing a feed assessment program in Pacific salmon enhancement hatcheries"
---

## 🧬 Project Summary

**Lead(s):** Ian Forster  
**Division:** N/A  
**Section:** Nearshore Ecosystems  
**Location:** N/A  
**Status:** New  
**Theme:** Unspecified  
**PSSI Pillar:** Unspecified  

**Overview:**  
Fish feed is critically important to fish growth, physiological functioning
and fish health, and a major budget item for salmonid enhancement facilities
in BC (~ overall 1 million CAD/year). Feed is a perishable item, however. The
quality will change if feed is exposed to air, adverse conditions, or
prolonged storage time. Ingredients including proteins, lipids, vitamins, and
pigments are heat- and moisture-sensitive. Feed can degrade and become
conducive to mold growth when exposed to extended periods of high temperature
and/or humid conditions. Moreover, there has been significant refinement in
fish feed formulations to partially replace finite and expensive marine
ingredients, such as fish meal and fish oil, with less costly, possibly more
sustainable, and more stable supplies of terrestrial ingredients; these may
not necessarily be suitable for growing fish for enhancement purpose (Colombo
and Turchini 2021). The quality of marine ingredients also fluctuates with the
increasingly unpredictable ocean conditions. These, and other, uncertainties
highlight the need to establish a feed sampling program to verify feed quality
and relay potential concerns to suppliers such that rapid improvements can be
made.

In the past, SEP collaborated with the DFO Fish Nutrition Lab (then under Dr.
David Higgs), located in West Vancouver. Dr. Higgs was an expert in
understanding nutritionally related fish mortality events. As an example, he
was involved in identifying the role of zinc deficiency on Chinook cataract
development (Richardson et al. 1985). His laboratory was also instrumental in
providing feed quality assessments through the 1990’s and early 2000’s and the
analytical support program for assessing SEP’s feed supplies at West Vancouver
Laboratory (now the Pacific Science Enterprise Centre, PSEC) ended with Dr.
Higgs’ retirement, close to two decades ago. In contrast, the US Fish and
Wildlife Service agency (Abernathy Fish Technology Center) examines fish feed
received by enhancement hatcheries located in the US Pacific Regions and
generates a quarterly report by probing into feed proximate composition
(protein, fat, ash, moisture) and rancidity related parameters (peroxide
value, free fatty acids, thiobarbituric acid). It is not uncommon that the
results show deviations in fat and protein contents and elevated rancidity
levels (oil degradation) relative to the manufacturer ingredient label and
quality standard (i.e. Fish feed quality control report 2024). The goal here
is to establish a feed sampling program to provide advice (feed
quality/storage) for salmon enhancement facilities in BC, and communicate the
results internally and externally, and to assess the viability of a long-term
feed quality assessment program.

Abernathy Fish Technology Center: Fish feed quality control report for the
first quarter of FY 2024.

Colombo, S.M., and Turchini, G.M. 2021. ‘Aquafeed 3.0’: creating a more
resilient aquaculture industry with a circular bioeconomy framework. Reviews
in Aquaculture 13: 1156-1158.

Richardson, N.L., Higgs, D.A., Beames, R.M., McBride, J.R. 1985. Influence of
dietary calcium, phosphorus, zinc and sodium phytate level on cataract
incidence, growth and histophathology in juvenile Chinook salmon (Oncorhynchus
tshawytscha). Journal of Nutrition 115: 553-567.



[⬅ Back to Home](../index.qmd)
