---
title: "Genetic and epigenetic consequences of hatchery adaptation"
---

## 🧬 Project Summary

**Lead(s):** Eric Rondeau, Timothy Healy, Kyle Wellband  
**Division:** N/A  
**Section:** Molecular Genetics  
**Location:** N/A  
**Status:** New  
**Theme:** Unspecified  
**PSSI Pillar:** Unspecified  

**Overview:**  
Adaptation to hatchery environments is known to reduce the fitness of Pacific
salmon in their natural habitats. However, in integrated hatchery populations,
such as those operated by the Salmonid Enhancement Program, there is typically
limited genetic differentiation between hatchery- and natural-origin spawners
as a result of gene flow between the two habitats. As a results, the genetic
variation responsible for hatchery adaptation is generally poorly resolved.
Captive brood programs maintain spawners in the hatchery environment through
their entire lifespan. This independence from natural spawners should amplify
signatures of hatchery adaptation. The objective of this project is to
leverage historical sampling of captive Sockeye Salmon broods in the Pacific
Region to characterize the genetics architecture of hatchery adaptation.
Beginning from ~2000, samples from two captive broods (Cultus and Sakinaw
Lakes) will be sequenced with high-density genomic sequencing to identify
changes in the frequencies of genetic variants throughout the duration of the
captive brood programs. These data will be paired with epigenetic sequencing
understand the contributions of DNA methylation to domestication within
captive broods, and the relationship between genetic adaptation and epigenetic
differentiation between hatchery- and natural-origin fish. These links are key
to the project as epigenetic variation between hatchery- and natural-origin
salmon is thought to play a large role in the effects of hatcheries even in
integrated populations. Finally, high-density sequencing results will be
compared with parallel low-density assessments of genetic variation in the
captive broods to validate the performance of low-density markers in assessing
and monitoring genetic diversity through time in captive brood and populations
of conservation concern.



[⬅ Back to Home](../index.qmd)
