---
title: "Impact of genetic divergence on outbreeding depression in Chinook Salmon"
---

## 🧬 Project Summary

**Lead(s):** Eric Rondeau, Timothy Healy, Kyle Wellband  
**Division:** N/A  
**Section:** Molecular Genetics  
**Location:** N/A  
**Status:** New  
**Theme:** Unspecified  
**PSSI Pillar:** Unspecified  
**Speaker Theme:** Hatchery science  

**Overview:**  
Abundances of many Chinook Salmon populations are in decline. In extreme cases
of these declines, local populations are at the risk of extirpation, which may
suggest intervention through the introduction of spawners from non-native
populations (i.e., transplants), which is sometimes termed &quot;genetic rescue&quot;.
Transplanted spawners can provide a demographic boost to declining
populations; however, Chinook Salmon display local adaptation, such that non-
native spawners may be less fit than native spawners, posing a genetic risk to
the native population. Additionally, interbreeding between populations has the
potential to expression genetic incompatibilities between populations that
also cause a loss of fitness (i.e., outbreeding depression). The consequences
of outbreeding in Chinook Salmon are poorly understood, and are highly
relevant to best practices for transplantation/genetic rescue. The objectives
of the proposed project is to collect gametes from four populations of Chinook
salmon displaying a range of genetic differentiation, conduct artificial
crosses within and among populations, and assess the hatching success and
physiological performance of the offspring from these crosses. We hypothesize
that negative outcomes of interbreeding are proportional to the genetic
differentiation among populations. A key question addressed by this experiment
will be whether or not interbreeding within a conservation unit produces
negative fitness outcomes.



[⬅ Back to Home](../index.qmd)
