---
title: "Restoring freshwater connectivity for Pacific salmon"
author: ""
toc: true
---

## 📋 Project Summary

**Lead(s):**   
**Division:**   
**Section:**   
**PSSI Pillar:**   
**Session(s):** Data And Modelling To Support Decision Making  
**Presentation Date(s):** December 11, 2025  
**Speakers:** Nick Lapointe  
**Overview:**  
The Restoring freshwater connectivity for Pacific salmon project by the Canadian Wildlife Federation is a continuation and expansion of their current BCSRIF project (BCSRIF_2019_137). The goals of the 2023-2026 project are to develop up to seven indigenous led watershed connectivity remediation plans in Pacific salmon habitat; update three existing watershed connectivity remediation plans; improve the habitat suitability modelling and assessment techniques for BC salmon to allow for better prediction of important spawning and rearing habitat areas disconnected by both longitudinal and lateral barriers in conjunction with UNBC; identify and rank the most important barriers to fish passage caused by rail infrastructure and initiate development of an action plan to restore access to spawning and rearing habitat that is currently cut off by rail stream crossings; and improve the knowledge and application of best practices for stream crossings among practitioners in government and the private sector to prevent future unintended fragmentation of habitat through the development of a short course and supporting resources relating to stream crossings. Target areas for watershed plans include the Bowron River and Quesnel River watersheds as well as other yet to be determined.   

